### ISSUE TITLE
Mails from POP3 accounts are downloaded over and over again

### ISSUE THREAD

**Issue by curiosityseeker** [eyalroz/removedupes#101]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1794611

The add-on seems to be the culprit as **manually** removing the duplicates solves the problem.

**Comment by eyalroz** [comment]
Well, my extension doesn't ever try to trigger POP3 download; plus, repeated downloads shouldn't bring you the same messages multiple times, unless there's something wrong with your popstate mechanism (which, again, the extension does not touch).

**Comment by curiosityseeker** [comment]
I'm sure that your add-on doesn't trigger POP3 downloads. However, isn't it possible that something goes wrong if it comes to deleting the duplicates? I mean it was very notable that in the numerous cases when I deleted the duplicates with your add-on, they were downloaded again when Thunderbird looked for new mails. As soon as I deleted the duplicates manually, the problem was gone. So something must be different ...

**Comment by eyalroz** [comment]
Well, I'll first say that the extension has been in existence for 15 years now; and the message deletion mechanism has not changed, so my intuition is that this is something specific to your setup. However, I don't want to discount the possibility that it could be my code's fault in some indirect way.

If you could offer exact reproduction instructions, on a clean profile with only my extension installed, that would help. Also, can you tell me whether you were moving messages to a trash folder, or properly deleting them? And what you chose as the trash folder?

**Comment by curiosityseeker** [comment]
You are right, I was wrong. The problem suddenly came back even with your add-on disabled. So what I observed was nothing than unfortunate coincidences. Sorry for the noise!

**Comment by eyalroz** [comment]
@curiosityseeker : It's quite alright, and I appreciate you coming back to close the bug :-)

I would also appreciate it if you would make a comment to that effect on the Bugzilla page you linked to.
