### ISSUE TITLE
Nothing happens when I click the Remove Duplicate button or select duplicate removal on the menu

### ISSUE THREAD

**Issue by SprintSerwis** [eyalroz/removedupes#102]
When I select "All Copies", the OK button does not work, neither with the "Delete Forever" option, nor with the "Move to Trash" option.
![duplicate](https://user-images.githubusercontent.com/22002477/198603366-6d40af56-ba7b-4b39-8766-c3602f1fe90a.png)

**Comment by eyalroz** [comment]
This is intentional. If you select all copies for keeping, that means you're not removing any duplicates. If that's what you want, you are **Cancel**ing your dupe removal, and that's what you should press.

If you want to _remove_ all copies, you need to select None.
