### ISSUE TITLE
Duplicates not recognised despite identical message IDs

### ISSUE THREAD

**Issue by kriegaex** [eyalroz/removedupes#103]
Plugin version: 0.5.2b4.

I have duplicates in the "Sent" folder (or subfolder thereof) vs. the "Inbox" folder (or subfolder thereof), because in old times - before switching from POP3 to IMAP - I used to sent myself BCC messages. Now, after switching to IMAP, I would like to get rid of the old duplicates. Even if I reduce the settings to just comparing the message ID (or sender + message ID) and make sure that the "Sent" folder is **not** ignored, the duplicates are not being found.

![image](https://user-images.githubusercontent.com/1537384/202020242-b29dc555-706d-49e7-b0c6-98efdadf760c.png)

![image](https://user-images.githubusercontent.com/1537384/202020379-d594021e-c6b3-47e9-a9e7-97c6d94a0c43.png)

When I check the corresponding messages' source code and look at the message headers, the message IDs are identical, e.g.

```text
Message-Id: <20221111200945.4F68A78C01A7@dd19710.kasserver.com>
```

I would also like to remove duplicates across accounts as described in #95, but this simple case here is within a single IMAP account.

**Comment by eyalroz** [comment]
First - removing across accounts does work. In #95 it was established that there were slight differences reported between the messages.

As for this issue itself: Generally, duplicates should be found in your scenario. I've just tried the following:

1. Made sure the settings are the same as yours
2. Created a new local folder named F1
3. Copied a message from the Sent folder to F1
4. Selected the two folders: F1 and Sent
5. Initiated a duplicate search

... and I got the two messages as dupes.

So, we need to figure out what's wrong in your case. Please tell me...

1. Whether you get any messages in the Error console (on the main menu, under Tools | Develoepor Tools) when you perform the dupe search, that mention "removedupes" or "Remove Duplicates". To do so, you may want to first clear the console, then perform the dupe search and see if some messages appear.
2. Whether you see this behavior among local folders or IMAP folders, or perhaps one folder is in an IMAP account and another one is local.
3. Whether the dupe search also fails if you copy the two messages to a new, separate, folder, and search for dupes in that folder only.

**Comment by kriegaex** [comment]
1. No errors, only two warnings about HTML "quirks mode". These seem unrelated.
2. Both folders are IMAP folders. But that does not matter. Even if I copy the two messages into the same IMAP folder or the same local folder, the identical message ID will not be detected, only other criteria like sender, date etc. This looks like a bug with regard to message ID specifically.
3. It does fail, see above.

**Comment by eyalroz** [comment]
@kriegaex : You get to choose where duplicates are moved - there's a drop-down-list box for that on the review dialog.

So, if we see the failure even in a local, I think the next phase could be - if you're willing - for you to send me a zipped copy of the local folder with just two messages, which are supposed to be duplicates, but are  not detected as such. I realize of course this might be a problem w.r.t. privacy, so this is up to you.

**Comment by kriegaex** [comment]
> @kriegaex : You get to choose where duplicates are moved - there's a drop-down-list box for that on the review dialog.

Well, that it true, but when selecting the option not to delete but to move to a folder, I thought that pre-selected folder is always that of the same e-mail account and not that of another one. It is somewhat counter-intuitive, but now that I know it, I can take care of it. Just strange that I need to do that manually every time I want to remove dupes.

> So, if we see the failure even in a local, I think the next phase could be - if you're willing - for you to send me a zipped copy of the local folder with just two messages, which are supposed to be duplicates, but are not detected as such. I realize of course this might be a problem w.r.t. privacy, so this is up to you.

Any normal e-mail I would send to you, but the one I tested contains sensitive pricing data I sent to a client. I will try to find another case which is less confidential and then send you the folder.

**Comment by eyalroz** [comment]
The message IDs were different, so - no bug.

**Comment by kriegaex** [comment]
> First - removing across accounts does work.

That might be true, but I cannot seem to get it working within a reasonable time frame, because despite me having set the option to always download the full IMAP folders and buffer them locally, TB always re-downloads thousands of messages from the IMAP server when starting a compare action, even though I am just comparing header information, not the number of lines or content of e-mails. Is there any way to speed up the process wiuthout me having to wait for hours to let it finish syncing folders it has synced many times before during previous dupe checks?

I know the question is not directly related to this closed question, but maybe you can still give me a hint. Thank you.

**Comment by eyalroz** [comment]
@kriegaex : Please migrate this comment to a new, separate issue about TB re-downloading message during a dupe check. One problem per page...
