### ISSUE TITLE
TB re-downloading all messages during dupe check for IMAP accounts

### ISSUE THREAD

**Issue by kriegaex** [eyalroz/removedupes#104]
> First - removing across accounts does work.

That might be true, but I cannot seem to get it working within a reasonable time frame, because despite me having set the option to always download the full IMAP folders and buffer them locally, TB always re-downloads thousands of messages from the IMAP server when starting a dupe check, even though I am just comparing header information, not the number of lines or content of e-mails. Is there any way to speed up the process without me having to wait for hours to let it finish syncing folders it has synced many times before during previous dupe checks?

_Originally posted by @kriegaex in https://github.com/eyalroz/removedupes/issues/103#issuecomment-1327471379_

**Comment by eyalroz** [comment]
I don't try to obtain the body of a message unless I need to. But - I do need the headers. So I do call: `ImapService.selectFolder()` and the IMAP folder's `getMessages()` method. There's no inherent reason for any re-downloads - so it's likely a TB mis-feature.

**Comment by romykl** [comment]
I can also confirm this TB misbehaviour, which seems independent of this dedupe extension. TB re-downloads all messages after a dupe check and delete in an IMAP account, thus cancelling the cleaning work done by this extension. I guess that TB does not transfer the cleaning and deletion to the IMAP server before it starts syncing its old unupdated situation from the server to the TB client. So TB has problems both 

- to update IMAP accounts from the server to the TB client and 

- the other way around: from the TB client back to the server.

**Comment by eyalroz** [comment]
@romykl : Is there something special about the IMAP server you're using?

I don't think I can really second-guess or circumvent TB on anything - I use its internal APIs to iterate the folders and also to delete messages, so if it misbehaves - I'm basically helpless.

**Comment by romykl** [comment]
The only Workaround I found for it was to copy the concerned folders to local files, then do the deduplication and finally copy them cleaned back into the account deleting the previous version before.

**Comment by kriegaex** [comment]
A few months back, this and other issues cost me days to deduplicate my messages in several IMAP accounts. I do not remember exactly how I made it work _without_ moving messages to local folders and deduplicating them there, but finally I got everything cleaned up. I think it was some kind of lag with expunging messages on the server, because I had so many folders and thousands of messages. But finally, Thunderbird finished its job, and now I have a clean message database.

I also cannot remember, but I think I might have compressed and (where necessary) repaired folders after deduplication. Sorry for having no better description for you, I am just trying to inspire hope that this is possible, just painstakingly slow. But for the life of me, I cannot remember how I made TB sync deletions up to the IMAP server. Was it just waiting or something else?

**Comment by romykl** [comment]
Concerning the lag you mentioned in duplicates on the server, I encounter the same problem: they are shifted by exactly one hour backwards. Therefore, I thought it happened due to summer/winter time shift. But this is just a guess. The 1 hour time shift makes it difficult to find these dupes side by side. I found no other way than ordering them by date and time and manually looking for the dupes shifted  by 1 hour. This is nerves wrecking. But no add-in software can help in such a case because there are no filters which can filter the dupes based on such a strange fixed time shift condition.

**Comment by kriegaex** [comment]
If you are talking about message IDs, which usually are the easiest and most exact way to differentiate messages, I experienced time stamps beinm baked into them by the IMAP server, making it impossible to use them as a unique criterion when trying to dedupe sent messages with auto-BCC to myself. In that case, I simply used a combination of sent date, subject, sender. I had to scroll through the results and check for exceptions, which was kind of tedious, but finally I managed to find all dupes. Try to experiment with the add-on settings, until you find a combination of criteria which help you to identify your dupes.

**Comment by Betterbird** [comment]
@eyalroz, can you explain/show your code a bit. Why do you call
https://searchfox.org/comm-central/rev/7d8c064a3fe5ff202eef140d30567fa7a6514095/mailnews/imap/public/nsIImapService.idl#36
and not, for example, `liteSelectFolder`? Is that necessary? Not being an IMAP expert, I'd think you can just iterate the messages in the folder without any special IMAP calls.
By `getMessages()`, you mean this:
https://searchfox.org/comm-central/rev/7d8c064a3fe5ff202eef140d30567fa7a6514095/mailnews/base/public/nsIMsgFolder.idl#66

**Comment by eyalroz** [comment]
> Why do you call [selectFolder() from `nsIImapService.idl`](https://searchfox.org/comm-central/rev/7d8c064a3fe5ff202eef140d30567fa7a6514095/mailnews/imap/public/nsIImapService.idl#36) and not, for example, liteSelectFolder?

Honestly? Because when I wrote that code, I didn't know about liteSelectFolder. Could it be that it didn't exist back then?

**Comment by eyalroz** [comment]
On Joerg's implicit suggestion, I'm changing `selectFolder()` into `liteSelectFolder()`, and we'll see what happens... please try a build.

**Comment by eyalroz** [comment]
@kriegaex : Could any of you please try a recent build? Just rename the `.zip` into an `.xpi`
[removedupes_0.5.3b3_tbird.zip](https://github.com/eyalroz/removedupes/files/11391306/removedupes_0.5.3b3_tbird.zip)

I'd like to know if the `liteSelectFolder()` helps.

**Comment by eyalroz** [comment]
Please reopen if the problem persists.

**Comment by eyalroz** [comment]
... and now, liteSelectFolder is gone - and so is the entire ImapService. Who knows what happened to it? :-(

**Comment by Betterbird** [comment]
Gone? Nothing happened:

https://searchfox.org/comm-central/rev/54d2a598d6481e38af22be3d11b0b5a941d66f3c/mailnews/imap/public/nsIImapService.idl#51
https://searchfox.org/comm-central/rev/54d2a598d6481e38af22be3d11b0b5a941d66f3c/mailnews/imap/src/nsImapService.cpp#211

**Comment by eyalroz** [comment]
Never mind, the service remains accessible through MailServices.
