### ISSUE TITLE
Apply "select first/last/etc." only to selected list items

### ISSUE THREAD

**Issue by kriegaex** [eyalroz/removedupes#107]
I have dupe checks with hundreds or thousands of potential duplicates. As I have no way to limit checks to certain senders or recipients of messages - in my case I am only interested in messages I sent myself - and also cannot specify to always prefer certain mail accounts or folders over others, I have to pre-select something like "keep first" and then check thousands of list entries for exceptions, of which there are many. I cannot filter by folder pairs. Also, if I shift-select a range of messages, I cannot apply "keep last" to just them, because it will re-apply my choice to **all** messages, i.e. my default "keep first" will be destroyed and I have to start over. More interactive ways to  work with the dupes list if there are many entries would be very helpful.

**Comment by eyalroz** [comment]
Hello @kriegaex , and sorry for the belated response. I'm super-busy and am just now getting around to my removedupes backlog.

> As I have no way to limit checks to certain senders or recipients of messages 

You could do that by moving messages from those senders or recipients to a separate folder, and searching for dupes only there.

Also, you can always manually change what to keep and what to discard by clicking the "v" marks / checkboxes / check dots of individual messages, in the "Keep" column.

Does this address your needs?

**Comment by kriegaex** [comment]
No, it does not address my needs, because it is a workaround, not a solution. A corresponding new feature would be a solution. I have several accounts, and potential matches can span nmultiple folders or even multiple accounts, i.e. moving them into a single folder would destroy the existing order, which of course I wish to retain.

**Comment by eyalroz** [comment]
> because it is a workaround, not a solution.

Not really. Because if we generalize your request - one may want to limit the checks only to messages in a certain range date; or with certain lengths in lines; or set of message IDs; or set of recipients etc. So really, the way to do this is to create a folder (albeit a virtual search folder) with what you want check.

**Comment by kriegaex** [comment]
We disagree then, but actually the **_virtual folder_** idea should make the workaround more viable for me. It is still not what I would wish for, but thanks for the helpful suggestion.

**Comment by eyalroz** [comment]
@kriegaex : If more users were to request this specifically, I would consider implementing it.

Having said that - I currently don't handle virtual folders at all. So, that's an issue to address...
