### ISSUE TITLE
Dupe check interrupted due to erros

### ISSUE THREAD

**Issue by kriegaex** [eyalroz/removedupes#108]
When trying to run a dupe check on certain folders or across certain mail accounts, no results are ever shown. Instead, I only see something like this in the error log:

```text
TypeError: db.folder is null MsgDBCacheManager.jsm:133:11
Uncaught TypeError: folderMessageHdrsIterator is undefined
    populateDupeSetsHash chrome://removedupes/content/removedupes.js:602
    processMessagesInCollectedFoldersPhase2 chrome://removedupes/content/removedupes.js:316
removedupes.js:602:17
Uncaught 
Exception { name: "NS_ERROR_FILE_NOT_FOUND", message: "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIMsgFolder.updateFolder]", result: 2152857618, filename: "resource:///modules/DBViewWrapper.jsm", lineNumber: 88, columnNumber: 0, data: null, stack: "updateFolderAndNotifyOnLoad@resource:///modules/DBViewWrapper.jsm:88:15\nopen@resource:///modules/DBViewWrapper.jsm:810:32\nshow@chrome://messenger/content/folderDisplay.js:849:19\nFolderPaneSelectionChange@chrome://messenger/content/commandglue.js:371:18\nonselect@chrome://messenger/content/messenger.xhtml:1:1\nMozTreeChildren/<@chrome://global/content/elements/tree.js:69:28\n", location: XPCWrappedNative_NoHelper }
DBViewWrapper.jsm:88
```

After that, the dupe check seems to continue in an endless loop, and I cannot access certain folders anymore, only seeing a "waiting cursor". In order to be able to access the same folders again, I have to restart TB, but then I am no longer in offline mode, and next time I want to start the dupe check, all IMAP folders are refreshed, which takes ages, see #104.

**Comment by kriegaex** [comment]
I am not 100% sure, but the problem seems to relate to the veeeery old problem of TB often corrupting folders, so you not only need to compress them, but also to re-open them manually in order for them to get re-indexed. Me having 100+ folders, this is next to impossible to do every few days. I have no idea, why they don't fix that issue, I can remember it since TB 1.x.

Anyway, the dupe checker seems to be unable to handle this problem and properly skip the folders it has problems with, continuing with the others, showing messages to the user what went wrong and which folders she should compress and re-index, so they are included next time. It just hangs, and the only way to access the folders again is to restart TB.

**Comment by planalp** [comment]
> When trying to run a dupe check on certain folders or across certain mail accounts, no results are ever shown. Instead, I only see something like this in the error log:
> 
> ```
> TypeError: db.folder is null MsgDBCacheManager.jsm:133:11
> Uncaught TypeError: folderMessageHdrsIterator is undefined
>     populateDupeSetsHash chrome://removedupes/content/removedupes.js:602
>     processMessagesInCollectedFoldersPhase2 chrome://removedupes/content/removedupes.js:316
> removedupes.js:602:17
> Uncaught 
> Exception { name: "NS_ERROR_FILE_NOT_FOUND", message: "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIMsgFolder.updateFolder]", result: 2152857618, filename: "resource:///modules/DBViewWrapper.jsm", lineNumber: 88, columnNumber: 0, data: null, stack: "updateFolderAndNotifyOnLoad@resource:///modules/DBViewWrapper.jsm:88:15\nopen@resource:///modules/DBViewWrapper.jsm:810:32\nshow@chrome://messenger/content/folderDisplay.js:849:19\nFolderPaneSelectionChange@chrome://messenger/content/commandglue.js:371:18\nonselect@chrome://messenger/content/messenger.xhtml:1:1\nMozTreeChildren/<@chrome://global/content/elements/tree.js:69:28\n", location: XPCWrappedNative_NoHelper }
> DBViewWrapper.jsm:88
> ```
> 
> After that, the dupe check seems to continue in an endless loop, and I cannot access certain folders anymore, only seeing a "waiting cursor". In order to be able to access the same folders again, I have to restart TB, but then I am no longer in offline mode, and next time I want to start the dupe check, all IMAP folders are refreshed, which takes ages, see #104.

I can confirm this problem on TB 102.5.0.

**Comment by eyalroz** [comment]
I guess TB is handing me a null folder handle, which I'm assuming can't happen. Will try to find the time this week to look into this.

**Comment by kriegaex** [comment]
Sounds great. If you cannot reproduce it and I happen to have the same problem again, we can easily do a desktop sharing session via Teamviewer or so. Then we can also log to your heart's content.

**Comment by eyalroz** [comment]
Fixed a while ago already, but didn't properly log and release the fix...

**Comment by kriegaex** [comment]
Well, fixed in Git is not the same as released and fixed for me as a user. If https://github.com/eyalroz/removedupes/releases/tag/v0.5.2 is the release containing the fix, you are not mentioning this issue in the release notes. Maybe you can edit the release notes correspondingly, if v0.5.2 is indeed the release containing the fix. 🙂

**Comment by eyalroz** [comment]
@kriegaex : That is the release. Now added this point to the release notes.
