### ISSUE TITLE
Remove Duplicates add-on not working v. 102.5.0 (32-bit)

### ISSUE THREAD

**Issue by GaTech76** [eyalroz/removedupes#109]
Found a few Email folders with duplicates (some in sub-folders) going back a long time. Just downloaded the add-on, restarted Thunderbird & ran the program. ONLY A FEW duplicates were found & copied to "Trash". Running the add-on again results in "No Duplicates found!" message.

Restarted Thunderbird & ran add-on again. Same result.
Restarted Thunderbird, compacted files & ran add-on again. Same result.
Restarted Thunderbird, ran "Repair Folder" to the folder with duplicates & ran add-on again. Same result.

What am I missing? Does the add-on need updating ???

Win7 x64, PoP mail server, earthlink isp

TIA
GaTech76

**Comment by eyalroz** [comment]
First - I'm glad that results are consistent :-)

Now, try playing with the comparison criteria you're using for the dupe search. Customize the toolbar to add the remove dupes menubutton, which has the choice of comparison criteria. Gradually remove criteria, until you start seeing the dupes you're interested in, then add criteria back to tighten the comparison. 

You will likely find that the messages differ slightly in send time, or number of lines; or the addresses or names are almost identical but not quite, etc.

**Comment by GaTech76** [comment]
Eyal,

Thanks for the suggestion. Problem solved. It was not obvious to me that I had to "customize" the toolbar by placing the "Remove Dupes" icon there, after which, a drop-down menu appeared allowing me to choose comparison criteria.

GaTech76

**Comment by eyalroz** [comment]
You can also set the comparison criteria using the Tools | Add-Ons tab, and pressing the wrench button for Remove Duplicate Messages to get the full add-on settings dialog.
