### ISSUE TITLE
Extension deletes permanently rather than moving to trash

### ISSUE THREAD

**Issue by pg5610** [eyalroz/removedupes#110]

**Comment by eyalroz** [comment]
1. Did you ensure the extension is configured to move to trash rather than delete permanently?
2. Do you get any messages in the Error Console?
3. Can you provide exact reproduction instructions?

**Comment by pg5610** [comment]
Thanks for the response.  I figured out the deletions went into the local folders trash folder when I was expecting them to go to the separate trash folders for each email account, which would be more handy, but at least I know where they went now.

**Comment by eyalroz** [comment]
You can set the destination folder in the dupe review dialog...

**Comment by pg5610** [comment]
Thank you I found that review dialog.  Very useful add on.  Thanks again.
