### ISSUE TITLE
UI Hangs with large sets of duplicate checks

### ISSUE THREAD

**Issue by BenjamenMeyer** [eyalroz/removedupes#111]
I recently ran into an issue where my TB or me somehow caused a recursive copy of my 20GB inbox (all under `Local Folder`) to be built and I ended up with 330 GB of data (yielding 19 levels of recursion, 17 of which have full copies and 1 has a partial copy as I killed TB in the middle of creating it - TB UI was non-responsive in the process but did keep repainting itself so never completely hung). I found this extension while trying to figure out how to clean up so many copies.

Essentially, the folder structure something like:
```
Local Folders\
Local Folders\Inbox\Folder1
Local Folders\Inbox\Folder2
Local Folders\Inbox\Folder2\SubFolder1
Local Folders\Inbox\Folder2\SubFolder2
Local Folders\Inbox\Folder2\SubFolder2\Inbox <- recursive point
Local Folders\Inbox\Folder2\SubFolder3
...
Local Folders\Inbox\Folder2\SubFolderN
Local Folders\Inbox\Folder3
...
Local Folders\Inbox\FolderN
```

Some folders have upwards of 75k emails or more; many have just a few thousand (2k-10k).

Running it initially on the top level "Inbox" yielded a hang; so I figured I'd move down to the lower levels and started at the last two levels ( the last full copy and the partial copy). After some playing around I got it to start deduplicating, but I still have some folders that have massive amounts. The TB UI seems to completely hang (even stops repainting) at times when it hits these massive folders. If I dedup other folders that don't include them then it seems to be relatively okay - TB might hang for a couple seconds but won't stop repainting and I will get a dedup box.

I opened the error console (all things enabled) and I don't see any errors being generated unlike #108.

Is there some way to add a `yield` into the process for various loops so that TB will at least remain responsive?
Having a UI that generates some feedback - not simply in the main TB UI's status bar - would also be an excellent addition where you could log what folds you're currently working on, number of emails found in them, etc.

**Comment by eyalroz** [comment]
> Is there some way to add a yield into the process for various loops so that TB will at least remain responsive?

In an earlier version, I had delegated the work to a different thread than the one running the UI, and I hit a bunch of TB multi-threadedness bugs in some situations; and so I had to "fold" myself back into single-threaded work.  That was... I don't know, 7 years ago or so. Maybe now I could do something else. I just need to find the time to work on these issues - which is difficult, as I'm burdened with other duties, both FOSS-related and to some extent due to the dire political situation where I live.

**Comment by BenjamenMeyer** [comment]
FYI - I think the majority of the issue might not be in the extension, but in TB itself as I was observing other issues in TB related to my process before the extension came into play - areas that would overlap with this extension like compacting the folder. See https://bugzilla.mozilla.org/show_bug.cgi?id=1808614.

Essentially, TB itself is highly inefficient with moving large amounts of messages around and the compaction and indexing portions seem to temporarily freeze the UI as they're no done in a background thread. If that was fixed in TB that would probably resolve the issue here too.

**Comment by eyalroz** [comment]
> Essentially, TB itself is highly inefficient with moving large amounts of messages around and the compaction and indexing portions seem to temporarily freeze the UI as they're no done in a background thread. If that was fixed in TB that would probably resolve the issue here too.

Tell me about it!

TB's backend is about 30 years old, and it shows. IMNSHO, a backend rewrite should be undertaken. In the mean time, you may want to consider switching to maildir: https://support.mozilla.org/en-US/kb/maildir-thunderbird


... regardless - considering your FYI, it seems like I can close this bug. Would you agree?

**Comment by BenjamenMeyer** [comment]
Yeah, I'll be watching the maildir support. I like MailDir a lot over mbox and use it with my mail servers.

Yes, considering the backend bug we can probably close this out because until that's resolved this probably can't do better or make it obvious where anything in this that could be improved; though a GUI to monitor while it's doing the search would be nice, and give some more immediate feedback, but that could be done in a separate issue.
