### ISSUE TITLE
Allow ignoring specific messages based on criteria such as `From`/`To` header

### ISSUE THREAD

**Issue by Destroy666x** [eyalroz/removedupes#113]
As the title says, it would be nice if settings had some `Ignore xyz` kind of textboxes with possibility to ignore all emails meeting the criteria, where `xyz` is for example `From` or `To` header.

**Comment by eyalroz** [comment]
The comparison logic could be made endlessly more complex. But - is it useful enough to implement and include in the extension?

For your specific case:

1. Find the emails meeting the criteria.
2. Move them to a temporary folder.
3. Perform dupe removal on the remaining messages.
4. Copy the special emails back from the temp folder

Would that not work for you?

**Comment by Destroy666x** [comment]
That's a lot of steps to do, assuming you have more than few addresses to ignore and would like to do it semi-regularly to clean.

**Comment by eyalroz** [comment]
> That's a lot of steps to do, assuming you have more than few addresses to ignore and would like to do it semi-regularly to clean. 

Create a search folder using these addresses, and you no longer have to type in anything nor remember the addresses.

**Comment by eyalroz** [comment]
Let's put it this way... if I were to get several requests for this feature, I might add it. But so far, you're the only person with this specific request.
