### ISSUE TITLE
How to control which TRash folder deleted duplicates go into

### ISSUE THREAD

**Issue by TomfromTampa** [eyalroz/removedupes#116]
I have two computers. One one computer, when I delete duplicate emails they go into the Trash folder associated with the email account. On the other computer, they go into the Trash folder under Local Folders. I have also submitted a question in the Thunderbird Community to see if there is some obscure setting, but I don't think it's a Thunderbird issue because if I do a regular delete of an email, it goes into the correct trash folder on both computers. It seems to me that the addon is using some other criteria or setting to ascertain which Trash folder to use.

**Comment by eyalroz** [comment]
The dupe review dialog, which opens up when the dupe search is completed, lets you choose the target folder.

The logic for setting the default value for the target folder is:
```
function initializeFolderPicker() {
  var uri, msgFolder;
  try {
    uri = RemoveDupes.Prefs.get('default_target_folder', null);
    msgFolder = RemoveDupes.GetMsgFolderFromUri(uri, false);
  } catch(ex) { }

    uri = RemoveDupes.Removal.getLocalFoldersTrashFolder().URI;
    msgFolder = RemoveDupes.GetMsgFolderFromUri(uri, false);
  }
```
and the preference is set to the last folder you selected explicitly.

> Why doesn't it simply choose the Trash folder associated with the email account for which I am removing duplicates?

There's a separate action for that. And the choice of action should persist. Have you tried using it?

**Comment by TomfromTampa** [comment]
Quote: There's a separate action for that. And the choice of action should persist. Have you tried using it?

Please explain further what you meany by this.  Do you mean if when I am deleting duplicates for email account #1 and I specifically drill down to the Trash folder for email account #1 it will default to that Trash folder in the future without me having to specifically select it? And the same concept is true for email accounts #2 etc? In other words I would only have to make the explicit choice once? I'm aware that I could simply try this but it'd be simpler if you could just state it here.

**Comment by eyalroz** [comment]
The specific-choice default is global.

The point is, you don't have to use that. You can choose to move to the account's trash folder, without drilling down into it at all. A third possible action is complete deletion.

**Comment by TomfromTampa** [comment]
I'm going to have to say that's what I did and it didn't work. When I got to the deletion step, the "Move to:" option said "Trash", The very first time I tried this for email account #2, the duplicates were put in the Trash folder under local folders, not the Trash folder associated with email account #2. In my experimentation, prior to bringing this issue to your attention, I tried clicking on the down arrow next to Trash and selecting the Trash folder for email account #2. After that, I sort of gave up and reported this to you. Perhaps I muddied the water by overriding the default of Trash, but since that wasn't working, I thought I needed to do something else. So what do I need to do to get it to work the way you say it's supposed to work? I'm going to need to reset something somewhere and I don't feel like experimenting.   I already suggested doing a one time (for each email account) explicit selection of the Trash folder for that email account's Trash folder and hope that it remembers that, but you said that I shouldn't need to do that. By my response, I showed that your solution didn't work for me. Now maybe that means my Thunderbird setup is broken, but I don't know how that could have happened, and since when I do a straight deletion of an email Thunderbird uses the correct Trash folder, logic says that the problem only happens when I'm deleting duplicates. I'm just looking for a solution.

**Comment by TomfromTampa** [comment]
Just a couple of updates (non successful). I was guessing/hoping that something had gotten corrupted with my copy of Remove Duplicates, so I removed the add-on and then exited and restarted TB. Then I started another attempt to remove a duplicate email. I randomly chose email account 2 and when I got to the last step I left the Move to option at Trash and clicked on OK. The email was put in the Trash folder for email account 1, not 2. So no help there. 
One final point. I have version 0.5.2b4 of Remove Duplicates, but according to your web page the current release is 0.5.1b2, with 0.5.2b4 being shown as pre-release. Grasping at straws here; which release should I have?

**Comment by eyalroz** [comment]
> I'm going to have to say that's what I did and it didn't work.  When I got to the deletion step, the "Move to:" option said "Trash", 

It seems I haven't been clear enough in my explanation. You should _not_ use the "Move To:" action, which is the second of three. Instead, use the first one, "Move to account trash folder":
![Screenshot from 2023-03-23 21-57-42](https://user-images.githubusercontent.com/8672255/227336958-aea3384f-a2fc-443f-9875-5b7a679609e6.png)

The drop-down folder tree is only relevant to the second action, so it doesn't matter what's selected in it if the first action is chosen. Please try using this action and tell me whether it works. I just re-checked this on a couple  of IMAP accounts, and it did what it's supposed to...

**Comment by TomfromTampa** [comment]
Eyal: Here's the text from an email I sent to you on 3/23. I didn't enter it here (maybe I should have) so I'm pasting it in now. It relates to your update above about the "Move to account trash folder" option



I'm looking at the screen print you included below. I don't have the "Move to account Trash folder" option. I don't know how to do a screen print but my Duplicate message review screen looks a lot like the one on the home page for your add-on:
https://github.com/eyalroz/removedupes/

From left to right:

Delete permanently           Move to Trash Folder(with a pulldown that allows the selection of different individual folders)

You also said something about IMAP accounts. I only have POP accounts. If you need to see exactly what I see please tell me how to do a screen print.

I'll mention again that I'm not sure that I have the latest version of your add-on (please see my earlier comments on the issues page). Could that explain why my screen has different options than yours, or is that because I have POP accounts vs IMAP?

Tom Gordon

**Comment by eyalroz** [comment]
It was, indeed, my fault. I neglected to make a release with that change. Anyway, please try 0.5.2 from here:

https://github.com/eyalroz/removedupes/releases/tag/v0.5.2

I am now working on TB 102 compatibility (which should pretty much be there already, but still), so 0.5.3 may soon come out too.
