### ISSUE TITLE
Missing chrome or resource URL: resource:///modules/MailUtils.js

### ISSUE THREAD

**Issue by smitgd** [eyalroz/removedupes#117]
I see this ```Missing chrome or resource URL: resource:///modules/MailUtils.js``` when running with tb 102.9.1. I'm not sure if this is a problem or not. But if I change removedupes-common.js to reference  MailUtils.jsm instead of MailUtils.js I don't see the complaint printed to console.

**Comment by eyalroz** [comment]
Hello @smitgd ,

TBH, I've neglected the maintenance of this extension for the past few months. I hope to have the time next week to collect several "bugs" (= compatibility breakages) with recent versions and fix things. If I haven't done anything within a week, please ping me.

**Comment by eyalroz** [comment]
So, this particular issue should now be fixed on the development branch. Please try a beta build...
[removedupes_0.5.3b1_tbird.zip](https://github.com/eyalroz/removedupes/files/11189508/removedupes_0.5.3b1_tbird.zip)

(rename the `.zip` into an `.xpi`; GitHub doesn't accept XPI files)
