### ISSUE TITLE
Delete permanently option not working

### ISSUE THREAD

**Issue by braian87b** [eyalroz/removedupes#122]
Hi, If I pick the delete permanently option for over moving to Trash or other folder the emails are not getting deleted.
This was after the latest update. before that it was working as expected.

Update: I also tested the move to folder and also doesn't work... moving to Trash works well but I don't want to move to trash the duplicates.

**Comment by biofers** [comment]
Same problem here, the check its not anymore selected by default and even clicking over it it doesn't work.

**Comment by braian87b** [comment]
Now its working, thank you.

**Comment by eyalroz** [comment]
@braian87b , would you be interested in helping me beta-test the next release or two of the extension? ... That would help me avoid gaffes such as releasing a version with a bug like this T_T
