### ISSUE TITLE
ja locale update for 0.5.2.1

### ISSUE THREAD

**Issue by kiki-ja** [eyalroz/removedupes#124]
@eyalroz 
Hi Eyal Rozenberg,

This time I am attaching the ja locale files for Remove Duplicate Messages 0.5.2.1.
I also sent the same files by email.

[remove_duplicate_messages_0521_ja_locale.zip](https://github.com/eyalroz/removedupes/files/11200156/remove_duplicate_messages_0521_ja_locale.zip)

An aside:
There are two duplicate lines in the en-US removedupes.dtd.

Thanks.
@kiki-ja

**Comment by eyalroz** [comment]
Hello @kiki-ja ,

Thanks so much for doing this... too bad babelzilla is dead :-(

I'll put these into a 0.5.2.2 release; hopefully a few more people can send me additional translations.

**Comment by eyalroz** [comment]
For v0.5.3, I might asked you to translate:

"Size (Headers & Body)".

**Comment by kiki-ja** [comment]
@eyalroz 

>"Size (Headers & Body)".

I attach the file with the translation added.
Please use it.

[remove_duplicate_messages_053_ja_locale.zip](https://github.com/eyalroz/removedupes/files/11221333/remove_duplicate_messages_053_ja_locale.zip)

Thanks.

@kiki-ja

**Comment by kiki-ja** [comment]
@eyalroz 

I have modified the Japanese locale file for v0.5.3.
Please use this attached.

[remove_duplicate_messages_053_ja_locale.zip](https://github.com/eyalroz/removedupes/files/11412168/remove_duplicate_messages_053_ja_locale.zip)

Thanks.

@kiki-ja
