### ISSUE TITLE
Failed moving messages to trash / Failed erasing messages (update 0.5.3.1)

### ISSUE THREAD

**Issue by himuy99** [eyalroz/removedupes#149]
Hey there, I'd like to report an issue I'm facing after the most recent update to the add-on.
After updating to ver 0.5.3.1 I am unable to move duplicate messages to the trash or to delete it.

Attempting to move duplicate messages to the trash folder results in this error:
![image](https://user-images.githubusercontent.com/65601468/236732897-0e76e4f1-5717-4a41-9a8d-a4f3a45c13a0.png)

Attempting to delete the duplicate messages permanently results in this:
![image](https://user-images.githubusercontent.com/65601468/236732984-4c39cfe7-8e3a-475c-b604-f31a44f5cbf5.png)

**Comment by eyalroz** [comment]
Please check the Error Console (via Tools | Developer Tools on the menus, or with Ctrl+Shift+J), and copy any messages related to "removedupes", especially errors.

**Comment by himuy99** [comment]
Hi @eyalroz ,
Sorry, I was unaware of Thunderbird having Dev Tools for the logs.

After I removed the add-on and re-installed it to Thunderbird, the issue doesn't seem to occur anymore.
I am unable to reproduce the issue now so I can't provide any further info.

If I ever run into the issue again I will be sure to gather more information from the Dev Tools.
