### ISSUE TITLE
Looking for a named string with "getting_subsets" instead of "building_subsets"

### ISSUE THREAD

**Issue by tkoeck** [eyalroz/removedupes#154]
I use Thunderbird 102.11.0 with 0.5.3.2.

If I want to use the plugin I get some action below as an information for a few seconds, but then it doesn't do anything. And no window is poping up eventually.

Additionally, I have seen the following line in the TB error log

https://github.com/eyalroz/removedupes/issues : Unable to run script because scripts are blocked internally. 

Any idea why it isn't doing anything anymore?

**Comment by tkoeck** [comment]
![2023-05-18 16_26_08-Einstellungen](https://github.com/eyalroz/removedupes/assets/42435353/32e4f79b-9a1f-4c9c-aac7-cba08e67f5d7)

This will be shown for around 30 seconds on the bottom. And then it stops.

**Comment by eyalroz** [comment]
I have no idea what that means, actually. I vaguelly remember that string from the error console of FF or TB but not in relation to my extension...

Is there nothing in the Error Console from the removedupes extension itself?

Also, which versions are you using, of TB and of the extension?

Finally - does it run for you with a clean profile?

**Comment by tkoeck** [comment]
Hi,

thanks for the prompt answer. I did mention the used versions above. I found another exception.

```
Exception { name: "NS_ERROR_FAILURE", message: "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIStringBundle.formatStringFromName]", result: 2147500037, filename: "chrome://removedupes/content/removedupes-common.js", lineNumber: 67, columnNumber: 0, data: null, stack: "RemoveDupes.Strings.format@chrome://removedupes/content/removedupes-common.js:67:22\nRemoveDupes.StatusBar.setNamedStatus@chrome://removedupes/content/removedupes-common.js:95:34\nRemoveDupes.MessengerOverlay.reportRefinementProgress@chrome://removedupes/content/removedupes.js:649:25\nRemoveDupes.MessengerOverlay.refineDupeSets@chrome://removedupes/content/removedupes.js:715:36\nRemoveDupes.MessengerOverlay.processMessagesInCollectedFoldersPhase2@chrome://removedupes/content/removedupes.js:293:32\n", location: XPCWrappedNative_NoHelper }
​
columnNumber: 0
​
data: null
​
filename: "chrome://removedupes/content/removedupes-common.js"
​
lineNumber: 67
​
location: XPCWrappedNative_NoHelper { QueryInterface: QueryInterface(), filename: Getter, name: Getter, … }
​
message: "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIStringBundle.formatStringFromName]"
​
name: "NS_ERROR_FAILURE"
​
result: 2147500037
​
stack: "RemoveDupes.Strings.format@chrome://removedupes/content/removedupes-common.js:67:22\nRemoveDupes.StatusBar.setNamedStatus@chrome://removedupes/content/removedupes-common.js:95:34\nRemoveDupes.MessengerOverlay.reportRefinementProgress@chrome://removedupes/content/removedupes.js:649:25\nRemoveDupes.MessengerOverlay.refineDupeSets@chrome://removedupes/content/removedupes.js:715:36\nRemoveDupes.MessengerOverlay.processMessagesInCollectedFoldersPhase2@chrome://removedupes/content/removedupes.js:293:32\n"
​
<prototype>: ExceptionPrototype { toString: toString(), name: Getter, message: Getter, … }
​​
columnNumber: 
​​
data: 
​​
filename: 
​​
lineNumber: 
​​
location: 
​​
message: 
​​
name: 
​​
result: 
​​
stack: 
​​
toString: function toString()
​​
Symbol(Symbol.toStringTag): "Exception"
​​
<get columnNumber()>: function columnNumber()
​​
<get data()>: function data()
​​
<get filename()>: function filename()
​​
<get lineNumber()>: function lineNumber()
​​
<get location()>: function location()
​​
<get message()>: function message()
​​
<get name()>: function name()
​​
<get result()>: function result()
​​
<get stack()>: function stack()
​​
<set stack()>: function stack()
​​
<prototype>: Object { … }
```

What do you mean with a 'clean profile'? I would have to download all my emails again with it?

**Comment by eyalroz** [comment]
Please try this build:
[removedupes_0.5.3.3b1_tbird.zip](https://github.com/eyalroz/removedupes/files/11509710/removedupes_0.5.3.3b1_tbird.zip)

I think I figured it out.

> What do you mean with a 'clean profile'? I would have to download all my emails again with it?

I mean a profile you create anew in TB. Typically without downloading anything, but possibly using the same Local Folders or same IMAP account so that you have access to some messages.  But - don't do that now, try the new build.

**Comment by tkoeck** [comment]
Yes, the beta seems to work. Thanks.

**Comment by eyalroz** [comment]
@tkoeck : This situation is partially the result of me not having beta testers for this extension. That's how several minor issues have snuck in to the release of 0.5.3 which I've had to fix with point releases :-(
