### ISSUE TITLE
Deleted All Messages in Folder

### ISSUE THREAD

**Issue by edvbevan** [eyalroz/removedupes#165]
Hi, there,

I have just run remove dupes in a gmail account in t-bird 102.12.0 on my mac, which had folders with messages from various other accounts.

In most folders, duplicates were found and moved to the deleted items folder, but in one particular folder, all the messages have been moved to deleted items.

I have two questions - why might that have happened in that folder only - and is there a way to return the messages to their original folder, and try it again with different criteria?

The comparison criteria are author, sent time, size and subject, and I am NOT skipping the special folders...

Cheers,

Ed

**Comment by eyalroz** [comment]
No reply for a month. If you can answer my question, I'll gladly reopen.

**Comment by edvbevan** [comment]
Hi,
I have not been able to reproduce the action, as I would need to put all the emails back into their original folders and start again.
Thanks anyway.
If I do manage to reproduce the effect, I’ll be in touch.

--
Warm Regards,
Ed Bevan,
***@***.******@***.***>


From: Eyal Rozenberg ***@***.***>
Date: Saturday, 15 July 2023 at 00:38
To: eyalroz/removedupes ***@***.***>
Cc: edvbevan ***@***.***>, Author ***@***.***>
Subject: Re: [eyalroz/removedupes] Deleted All Messages in Folder (Issue #165)

No reply for a month. If you can answer my question, I'll gladly reopen.
