### ISSUE TITLE
Missing prefs in 0.5b3 ??

### ISSUE THREAD

**Issue by smitgd** [eyalroz/removedupes#17]
I don't see any prefs for skipping "special" folders and other folder options and I don't see the pref for time resolution like in the old <=68 only version. Are all addon prefs supposed to now be accessible via the toolbar button?
Sorry if known bugs but I didn't see these explicitly in the issue list (except for one that might be referring to this).

Also, is there any explanation for the "Set original message folders(s) for the next duplicate search"? I don't understand what this means.

I  built your "development" branch and don't see any prefs when I install it. Thought maybe it fixed the missing prefs but didn't see any prefs and the button never appeared.

I've been working on another project here https://github.com/smitgd/addon-copyfolder-tb-esr68 and wanting to adapt it to tb 78 like you have so I've been using yours as an example. The copyfolder addon is a lot simpler than yours but has some in common. I think between your removedupes and the copyfolder addon, they might provide a good workaround for a long standing and difficult to fix tb bug https://bugzilla.mozilla.org/show_bug.cgi?id=538375

**Comment by eyalroz** [comment]
Oh, you're barging into an open door...

The preferences are there, but are only accessible using the menu bar (or, in a raw form, the config editor). See these two issues:

* https://bugzilla.mozilla.org/show_bug.cgi?id=1662990
* https://bugzilla.mozilla.org/show_bug.cgi?id=1662992

about making them more visible and accessible.

**Comment by smitgd** [comment]
Ok, thanks! So it's under the tools menu. Guess I should have looked closer but it used to be visible after selecting Addons. But looks like the tb bugs have been dismissed as "invalid".

I do have a few more questions if you don't mind. I will send them via email.

**Comment by eyalroz** [comment]
See also:

* https://github.com/thundernest/addon-developer-support/issues/40
* https://github.com/thundernest/addon-developer-support/issues/41
