### ISSUE TITLE
Command: "Original festlegen" (german version)

### ISSUE THREAD

**Issue by MichaelEderKenbun** [eyalroz/removedupes#175]
Hi, 

what´s that command for and how is it used?

thanks
Michael

**Comment by eyalroz** [comment]
In English, it is "Set originals folders". 

What it does is the following: Usually, we look for sets of messages within the folders we search, which appear identical. But when we set an "originals folder" - we only look for copies of messages in the originals folder, i.e. if F_1 has the originals and we search for dupes in F2 and F3, and there's a message m2 in F2 and message m3 in F3 which are identical - they will not be considered for removal, unless there's an identical message also in F1.

Does this answer the question?

If it does, do you think the translation is good enough? Or - would you translate the phrase differently?

**Comment by MichaelEderKenbun** [comment]
thanks a lot.
The translation is good to understand with the example you gave.
three extra questions about this feature.
- is the selected originals folders visualized in any way?
- is it possible, to disable that feature and find all dupes in the selected folder
- clarification for me: thunderbird allows only to select one folder, right? So the extension can find dupes in one folder (with subfolders)

Are you a german native speaker (as I am obviously;-))?

**Comment by eyalroz** [comment]
Ich sprech-nicht Deutch  ... and that's probably not correct either. But I've had volunteer translators help me with various languages. Anyway,

> is the selected originals folders visualized in any way?

It used to be! I would turn that folder's row's background color to light yellow. But the TB people have rewritten things so many times under the hood that this capability got lost at some point. Once I get the button and the context menu item working again, I should go back to this as well.

> is it possible, to disable that feature and find all dupes in the selected folder

No and Yes. There's no specific "Clear originals folders setting" item, but you can:

1. Make a dummy search (e.g. of a special folder, and those are skipped) - which clears the setting.
2. Select the top folders you want to search, and use "Set originals folders" on these - that should have the same effect as clearing the setting. Except... that I haven't really tested that approach.

> clarification for me: thunderbird allows only to select one folder, right?

No, not right, you can select as many as you like.

...

hey! damn it! They broke the multi-folder selection as well! With every version they mess up the UI and make it worse. Sometimes they change things halfway back, like with the ridiculous monochromatic icons, but generally - TB's interface is really going down the toilet. Do you remember when it used to look like this:

https://images.betanews.com/screenshots/1057948436-1.png

plain and simple...

**Comment by MichaelEderKenbun** [comment]
Hi,

thanks again für your good answer.
Wouldn´t it be a good idea, to visualize the “Original Folder” in the Dialog: “Duplicate Massage Review”, that could also a good place to clear it.
Maybe a good feature request 😉.

I like the addon a lot, so if you need help in translating to German you can contact me.

Cu Michael


Von: Eyal Rozenberg ***@***.***>
Datum: Freitag, 14. Juli 2023 um 23:48
An: eyalroz/removedupes ***@***.***>
Cc: Michael Eder ***@***.***>, Author ***@***.***>
Betreff: Re: [eyalroz/removedupes] Command: "Original festlegen" (german version) (Issue #175)

Ich sprech-nicht Deutch ... and that's probably not correct either. But I've had volunteer translators help me with various languages. Anyway,

is the selected originals folders visualized any way?

It used to be! I would turn that folder's row's background color to light yellow. But the TB people have rewritten things so many times under the hood that this capability got lost at some point. Once I get the button and the context menu item working again, I should go back to this as well.

is it possible, to disable that feature and find all dupes in the selected folder

No and Yes. There's no specific "Clear originals folders setting" item, but you can:

  1.  Make a dummy search (e.g. of a special folder, and those are skipped) - which clears the setting.
  2.  Select the top folders you want to search, and use "Set originals folders" on these - that should have the same effect as clearing the setting. Except... that I haven't really tested that approach.

clarification for me: thunderbird allows only to select one folder, right?

No, not right, you can select as many as you like.

...

hey! damn it! They broke the multi-folder selection as well! With every version they mess up the UI and make it worse. Sometimes they change things halfway back, like with the ridiculous monochromatic icons, but generally - TB's interface is really going down the toilet. Do you remember when it used to look like this:

https://images.betanews.com/screenshots/1057948436-1.png

plain and simple...

**Comment by eyalroz** [comment]
I'll open a separate issue for your last request, since that would indeed be useful.
