### ISSUE TITLE
Thunderbird 115.2.2 

### ISSUE THREAD

**Issue by ondohotola** [eyalroz/removedupes#189]
I pushed the upgrade button and find that the interface of TB has been drastically misunderimproved.

Leaving that aside, I can't seem to be able to locate the icon to put on the top bar any longer.

Is there a way of tying RD to a key (combination), to avoid having to always access the pull down?

**Comment by LeonidMalakhov** [comment]
How can I make it working, maybe you can help me? 
I push remove duplicates in the context menu, but it never finds any duplicates...

**Comment by ondohotola** [comment]
You need to set up the "Message Comparison" experimenting with the values.

**Comment by eyalroz** [comment]
Please do not post unrelated comments/questions on this bug.

@ondohotola : No you don't have to enable any experiments, that has nothing to do with the extension, and it's not the subject of the bug you opened.

Indeed, TB has messed up its main toolbar and made it very difficult to add buttons to it; and there's no documentation for it, either.

For now - please use the menu bar or the right-click context menu to trigger a dupe search.

As for a shortcut key - accel+shift+p should work in the messenger window (that's Ctrl+Shift+p on Linux, not quite sure what the key combination is on Mac).

@LeonidMalakhov : If you believe the extension is not working, file a separate bug. However, it is almost certain that your messages are simply near-dupes. Relax your comparison criteria using the extension's options dialog and you should start finding dupes.

**Comment by LeonidMalakhov** [comment]
Dear Eyal

thank you very much for your help, now it is working, when I relaxed on of the rules. 

Pls advice, what does "accel" mean? What is this button? I cant find it on my keyboard :)

**Comment by ondohotola** [comment]
On the Mac it's Option-Shift-P and works, thank you very much.
