### ISSUE TITLE
Message Compare Add  a option “bcc list”

### ISSUE THREAD

**Issue by sharego** [eyalroz/removedupes#190]
Very usefully project. Current can choose "cc list" as a option, hope add option for "bcc list"

I use TB 115.1.1 on windows x86-64，Remove Duplicate Messages 0.5.4b5

Now, the configure as follow:

![微信图片_20230914161425](https://github.com/eyalroz/removedupes/assets/3061821/79b39074-895e-4d30-bb01-de21951946b1)

so, how many need it? is worth?

**Comment by eyalroz** [comment]
Well, you're the first person to ask for this since the extension was first published in... 2008 I think. I would definitely consider a pull request implementing this; and it shouldn't even be too difficult. But to do it myself I'd expect a couple more requests, I think.

**Comment by eyalroz** [comment]
@setnicka : Custom header fields is a different issue. Please open a separate one.

**Comment by eyalroz** [comment]
Closed for now - but if more people ask for this, I'll reopen.
