### ISSUE TITLE
Not finding duplicates: TB 115.3.3

### ISSUE THREAD

**Issue by lynnechapman** [eyalroz/removedupes#193]
Hi, just downloaded "Remove Duplicate Messages" for Thunderbird. I have a folder with over 75 messages duplicated. It found 2 then keeps saying no duplicates even though I can see them there!
Thanks

**Comment by griffinist** [comment]
I'm having the same problem. I am using TB 115.3.1, Rocky Linux 8.8, Extension version 0.5.4b5. I've tried clicking "Remove Duplicates" from the Tools menu, right click on folder name, and run it with a pair of duplicate messages selected and all messages in folder selected. Thank you.

**Comment by eyalroz** [comment]
Hello.

As you may be aware, there's a war around here right now, and I have other obligations, so I'm not as quick as I should be to reply to bug reports. 

To the point, though - your messages are not duplicates, they are only almost-duplicates. Relax the comparison criteria gradually, until you begin to see dupes, then restrict them again carefully.

Very often, the messages differ by an empty line or two which Thunderbird erroneously adds at the end, so a good criterion to discard first is Number of Lines.

If you don't see duplicates even with all comparison criteria cleared - please reopen the issue (although I very much doubt that will happen - I get this question a lot.)

**Comment by griffinist** [comment]
Thank you! And my apologies. I did not realize you are in or near a war zone. My heart goes out to you. May you and your loved ones be safe. 

I copied one email message and save them each to EML files. xxdiff said they were identical. Generating them EML files may remove and inconsequential differences. Them I turned off all criteria except Message ID, and it found the duplicates. I added criteria one by one and found for these two messages, if any of Body, Size (Headers & Body) and Number of lines in message were check, the messages were not duplicates. I then checked the size in TB and sure enough the copy was almost 6 x the size of the original! There were no visible differences in the preview pane in either the header or body. And the saved files were identical.

Thank you for both your help and this wonderful extension.

**Comment by eyalroz** [comment]
@griffinist : I realize this is annoying, but I have to use more stringent comparison criteria by default, because it is better that some people fail to remove some duplicates, than for other people to remove non-duplicates due to an overly lax comparison. I have no choice but to err on the side of caution.

**Comment by griffinist** [comment]
I agree completely. It looks like TB is doing something internally that counter-intuitively messes with some criteria in a not-too-obvious way. All the more reason to be cautious. Thanks again for all your effort and insight. I hope this bug report comes up at the top of searches for other users.
