### ISSUE TITLE
Remove Duplicates Menu Option Disappears

### ISSUE THREAD

**Issue by nikga123** [eyalroz/removedupes#207]
Hello, 

I am running Thunderbird 115.7 and Remove Duplicate Messages version 0.5.4b5. Overall, Remove Duplicate Messages performs as it should. 

However, what I am running into is the Remove Duplicates menu option randomly disappears as if the add-on was turned off. The menu option comes back after turning off, and then back on, the add-on. Not a world-ending issue, but prior to updating to 115.7, this was not occuring.

Thank you.

**Comment by berti34** [comment]
Hi,
I had to deactivate and re-activate the extension. That helped me. The Menu point is back again...
Greetings

**Comment by eyalroz** [comment]
So, this is probably a Thunderbird bug :-(
