### ISSUE TITLE
Thunderbird Addons link 

### ISSUE THREAD

**Issue by gizmecano** [eyalroz/removedupes#21]
The link indicated in the `README.md` file and the repository front page (_i.e._ [`remove-duplicate-messages-alte`](https://addons.thunderbird.net/en-US/thunderbird/addon/remove-duplicate-messages-alte/)) seems to not work at this time.

Maybe can this issue be related to the recent changing of name? Or does the extension been removed?

**Comment by eyalroz** [comment]
@gizmecano : Fixed. It was a rename on ATN.
