### ISSUE TITLE
Support for Thunderbird Versions beyond v115

### ISSUE THREAD

**Issue by meichthys** [eyalroz/removedupes#215]
Currently the add-on isn't able to run in Thunderbird versions beyond v115. 
I'm not sure what would be involved in getting this to run on newer versions. 
Perhaps just updating the manifest.json???

**Comment by eyalroz** [comment]
First note, that Thunderbird's project leadership has made a strategic decision to restrict extensions further and further, to reach a state similar to what happened with Firefox a few years back.  Also, they have crippled  certain aspects of the application regardless of extensions, e.g. preventing users from selecting multiple folders at once. For these reason, my extension isn't fully-functional already in Thunderbird v115. Version 102 was the last one I managed to get to work fully.

As for versions beyond v115 - when we are close to the next release (which should be v128 IIANM), I will look into what has been broken by recent changes and try to adapt to the new version. Please feel free to reopejn when TB v128 is in beta.
