### ISSUE TITLE
Much smaller number of duplicates deleted across different folders

### ISSUE THREAD

**Issue by KC-T** [eyalroz/removedupes#216]
I am using Thunderbird 115.11.0 (64-bit) and Remove Duplicates 0.5.4b5.

I have a lot of duplicated folders. Executing Remove Duplicates with "folder" in the settings menu unchecked can only scan through a small number of folders, and report duplicates up to not more than 2000 messages covering more than one folder. A pop up window will appear to ask for confirmation of deletion. The number stated there is not for that particular folder. The pop up window only appeared once, while past version can pop up many windows for the many folders. It means that I have to execute Remove Duplicates many times. This should be a bug to be fixed.

**Comment by KC-T** [comment]
I confirm that in spite of the bigger number of duplicates reported and confirmed to be deleted, only those in the first folder are deleted.

**Comment by KC-T** [comment]
Not completed actually.

**Comment by eyalroz** [comment]
The duplicate search has worked basically the same for many years, and I have not gotten these complaints.

> Executing Remove Duplicates with "folder" in the settings menu unchecked can only scan through a small number of folders, and report duplicates up to not more than 2000 messages covering more than one folder.

That is not true. The extension is known to scan over 100 folders with over ~120,000 messages and many thousands of dupes.

> A pop up window will appear to ask for confirmation of deletion. The number stated there is not for that particular folder. The pop up window only appeared once, while past version can pop up many windows for the many folders. 

There is only one confirmation dialog, for all of the folders you've scanned. For every scan started - one dialog pops-up at the end. This is how the extension works now, and this is how it worked in the past.

> It means that I have to execute Remove Duplicates many times. This should be a bug to be fixed.

If you can share a link to a a set of message folders, with which this bug can be reproduced - I'll try to reproduce it on my machine. But I am almost certain that what you're describing is some issue with your Thunderbird installation, machine, or IMAP folder.

**Comment by KC-T** [comment]
Thank you for the reply. I am a long time user of Remove Duplicates. My observations of the differences between the past and the current should be accurate.

I have written some codes to directly remove the duplicates across many folders (due to recovery of multiple backups) at the email server side (dovecot) to resolve the big issue.

I have continued to use Remove Duplicates and found that the previous issues have gone. The previous issues could possibly be due to Thunderbird.

**Comment by eyalroz** [comment]
Indeed, it's possible that something in Thunderbird itself disrupted the extension's operation. If you see this problem again, please reopen - but explain how one can reproduce the problem.
