### ISSUE TITLE
Remove Duplicate Messages 0.5.4 Beta 5 & Thunderbird 115.11.1: Select Multiple Folders and perform a dupe search across multiple folders not possible

### ISSUE THREAD

**Issue by drueppela** [eyalroz/removedupes#218]
I want to search duplicate messages across my whole e-mailaccount (more then 2.000 folders).

With the combination

Duplicate Messages 0.5.4 Beta 5
&
Thunderbird 115.11.1

it seems not possible to select multiple folders and as consequence it seems not to be possible to perform a dupe search across multiple folders..

Also see: https://bugzilla.mozilla.org/show_bug.cgi?id=1817605

**Comment by eyalroz** [comment]
This is something that Thunderbird used to support - and should support, but was recently dropped. The removedupes extension always supported, and continues to support, searching multiple folders for duplicates; but it doesn't handle folder selection - that's the Thunderbird application's business, not an extension's.

**Comment by PackElend** [comment]
looks like it is fixed https://github.com/eyalroz/removedupes/ but thunderbird 128 might be not that stable

**Comment by eyalroz** [comment]
This is not a removedupes bug, so closing.

Thunderbird 128 seems to have restored multi-folder selection; and there is a new version of removedupes which supports TB 128, so you can use that...
