### ISSUE TITLE
Issue Removing Duplicates

### ISSUE THREAD

**Issue by mystik1** [eyalroz/removedupes#220]
I wonder if my problem is relating to using the Owl addon for Exchange email...

I removed all the duplicates using the addon, but they are still there in my TB.  Now when I go into the addon to try removing again, it says there are none.  What to do?

Thank you very much.

**Comment by bmazak** [comment]
New to program.  How to use?  No instructions visible to show how to start the process.  Does it do a folder or all folders?

**Comment by eyalroz** [comment]
If you've installed the extention, you can now right-click a folder (or a group of folders if you can select them) and on the context menu, choose "Remove Duplicates". The add-on settings dialog lets you control which comparison criteria to use and some other tweaks, e.g. whether to search special folders.

**Comment by bmazak** [comment]
Hay, thanks. I found it before I got this, but, thanks for the reply.  Great extention.  Hope you will add more instructions so we don't have spend time tring to figure out how to use it.
