### ISSUE TITLE
Thunderbird 128 ESR compatibility problems

### ISSUE THREAD

**Issue by tkoeck** [eyalroz/removedupes#223]
Thunderbird 128 ESR compatibility problems.

**Comment by eyalroz** [comment]
Yes, you're absolutely right. Unfortunately, I am tied up in protests against the continuing war on Gaza (plus my day job), and have not yet found the time to perform the update. I hope to be able to do so something this month, but no promises.

**Comment by LamKarThess** [comment]
I think it's time to make the move so that the addon gets compatible with TB128.
Your addon is important for many users and they deserve the update.

**Comment by FrankSchoe** [comment]
I admit - I would also be very happy about the update to TB128.
At the same time, I'm always surprised at the boldness with which some commentators demand a service for which they pay nothing. Many apps - like this - are free "gifts" to the community and it is up to the developer to decide if and when they take the time to develop these gifts to the next level.

**Comment by tkoeck** [comment]
> I admit - I would also be very happy about the update to TB128. At the same time, I'm always surprised at the boldness with which some commentators demand a service for which they pay nothing. Many apps - like this - are free "gifts" to the community and it is up to the developer to decide if and when they take the time to develop these gifts to the next level.

Well, yes, there is no 'debt' on the developer side.

That being said, the add-on seems to work after I just edited the manifest file for the newer version. So it doesn't seem to be a big change.

**Comment by confusedsushi** [comment]
@tkoeck if you already made that change, you might want to create a PR? Then someone might want to create an alpha release for the community for testing. This would take pressure from @eyalroz.

**Comment by LamKarThess** [comment]
@FrankSchoe @tkoeck 
As Thunderbird users for many years, we acknowledge the usefulness of some addons such as this and a few others.
There is no boldness from the side of the users to ask from the developers to update. The developers themselves, following the philosophy of supporting the open source applications, are obliged to update their apps (if not - this is boldness towards their users). it's also their choice and right to release their apps under subscription payment if they want.

**Comment by tkoeck** [comment]
> @tkoeck if you already made that change, you might want to create a PR? Then someone might want to create an alpha release for the community for testing. This would take pressure from @eyalroz.

I just adjusted the manifest.json in the add-on file (which is just a "zip file") to

"strict_max_version": "135.*"

I didn't test it extensively but it seems to work. If you already installed git on the PC and cloned it, you can create an MR.

**Comment by LamKarThess** [comment]
@tkoeck 
Thank you very much. Correction done.

**Comment by eyalroz** [comment]
Please try this build:
[removedupes_0.6.0_tbird.xpi.zip](https://github.com/user-attachments/files/16410831/removedupes_0.6.0_tbird.xpi.zip)

**Comment by LamKarThess** [comment]
@eyalroz 
I get the message " file is corrupt"

**Comment by eyalroz** [comment]
Try it through this link maybe:

https://github.com/eyalroz/removedupes/releases/tag/v0.6.0-b1

**Comment by LamKarThess** [comment]
@eyalroz 
The same
![2024-07-29_135044](https://github.com/user-attachments/assets/20f2b029-0ab8-46d6-a3ca-3cbe2051c710)

**Comment by LamKarThess** [comment]
@eyalroz 
I decompressed [removedupes_0.6.0_tbird.xpi.zip](https://github.com/user-attachments/files/16410831/removedupes_0.6.0_tbird.xpi.zip), I got the .xpi file and installed correctly

**Comment by LamKarThess** [comment]
@eyalroz 
I did duplicate some emails and tried. Works fine.

**Comment by LamKarThess** [comment]
@eyalroz 
My settings are
![2024-07-29_140005](https://github.com/user-attachments/assets/cd8b3091-4fe8-4588-908b-12ac699e3fbd)

**Comment by eyalroz** [comment]
> @eyalroz I did duplicate some emails and tried. Works fine.

> Can I help more?

Not really. I have not actually made significant changes for TB 128. Uploading this to AMO now.

**Comment by LamKarThess** [comment]
@eyalroz 
Thank you very much for your prompt actions. Made TB uders very happy.
We all hope for the best of
![Flag_of_Palestine svg](https://github.com/user-attachments/assets/134086cd-f8f2-4314-a285-91da5dedc449)

**Comment by eyalroz** [comment]
My actions were actually not that prompt... next year, please start poking me when a beta version is out.

As for Palestine - even if the war stopped now, there have been so many deaths and injuries already... and half of Gaza is piles of rubble. It'll take years just to clear away what's been destroyed. It's terrible.

Oh, but perhaps I should mention:

* https://donate.unrwa.org/gaza/
* https://www.msf.org/donate <- they don't have a separate donations channel for Gaza but they are active in the strip
* https://crisisrelief.un.org/opt-crisis

people's lives literally depend on the foreign aid. And - the US had cut all funding to UNRWA (other world states have as well, but they've restored it), which is a huge chunk of its funding, and UNRWA is by far the most active organization helping people on the ground in Gaza. They've also lost many people to Israeli fire.
