### ISSUE TITLE
Submenu "Extras"->"Add-on-Einstellungen" is doubled by removedupes

### ISSUE THREAD

**Issue by ungeahnt** [eyalroz/removedupes#23]
![grafik](https://user-images.githubusercontent.com/28572767/95102059-3347c480-0733-11eb-94ec-0e93873f6939.png)

The lower entry includes all other Add-ons and is also connected to the keyboard shortcut "g".

Thunderbird V68.12.1 (32-Bit), German

**Comment by eyalroz** [comment]
So, this is an issue with the Add-On loader, which the extension now uses. That is, I don't place the entry in the submenu myself. In TB 78 the problem no longer occurs, but it is a known issue with v68 (see link).

**Comment by ungeahnt** [comment]
Since the problem seems to be solved in V78, the request has been solved for me. I will certainly update to V78 within the next weeks/months. You can close this issue if you like.
@eyalroz thanks a lot for this great add-on!
