### ISSUE TITLE
What are the Default Message Comparison Settings?

### ISSUE THREAD

**Issue by rob-prime** [eyalroz/removedupes#230]
Hello!
When I first tried this add-on on a folder, it found duplicates.  Then I wanted to check the settings under "Message Comparison," ticked some more boxes, and ran the add-on again on the same folder.  Now it finds no duplicates in that folder.  I have turned off a bunch of Message Comparison options but I'm still getting "No duplicates found" as a result.  Can you tell us what the default settings are, and perhaps what exactly each option does?  Thanks!

**Comment by eyalroz** [comment]
> Can you tell us what the default settings are, and perhaps what exactly each option does? Thanks!

The defaults can be [found in `src/defaults/preferences/removedupes.js`](https://github.com/eyalroz/removedupes/blob/master/src/defaults/preferences/removedupes.js#L13) :

```
pref("extensions.removedupes.comparison_criteria.message_id", true);
pref("extensions.removedupes.comparison_criteria.send_time", true);
pref("extensions.removedupes.comparison_criteria.size", true);
pref("extensions.removedupes.comparison_criteria.folder", false);
pref("extensions.removedupes.comparison_criteria.subject", true);
pref("extensions.removedupes.comparison_criteria.author", true);
pref("extensions.removedupes.comparison_criteria.num_lines", false);
pref("extensions.removedupes.comparison_criteria.recipients", false);
pref("extensions.removedupes.comparison_criteria.cc_list", false);
pref("extensions.removedupes.comparison_criteria.flags", false);
pref("extensions.removedupes.comparison_criteria.body", false);
```
but they are somewhat arbitrary (and conservative, to avoid finding false dupes). Different scenarios merit different settings.
