### ISSUE TITLE
TB 115.15.0: after mail imports - doesn´t work in any folder

### ISSUE THREAD

**Issue by EiWasDann** [eyalroz/removedupes#231]
Had to reinstall TB on a new machine and accidentially imported the mails twice. Not working at all, just straight comes up with "No duplicate mails found."

**Comment by eyalroz** [comment]
You are likely comparing using overly stringent criteria. Sometimes TB adds an extra line of whitespace; or you're using the message flags for comparison, with some messages being read while others aren't; etc.

Relax the criteria until you find dupes, then slowly decide how to tighten them again.
