### ISSUE TITLE
Thunderbird POP account repeatedly downloads old emails. 

### ISSUE THREAD

**Issue by ReneLeB** [eyalroz/removedupes#233]
With a q.com POP account, Thunderbird 128.2.0esr (64-bit) started downloading many old emails. The settings are to not remove emails from the server until I delete them. I use filters to move emails from desired senders into local folders. I decided to remove the popstate.dat file from the profile for that account and then let Thunderbird synchronize. Of course, this resulted in downloading everything again. I ran the remove duplicates many times, but this function does not work well. It removes *some* duplicates while leaving many others that I manually delete. 

I have marked many folders "read," trying to let the synchronization of the popstate.dat file finish. I have also deleted many old emails, hoping this would remove them from the server so it doesn't download them again, but I am having trouble stabilizing the system. It would help if the remove duplicates function worked properly, but it does not. 

I also have a Gmail account that I access through Thunderbird, and I have never had this problem with it. I wonder if there is something flakey with the Centurylink q.com account, such as the server not recognizing the emails that have already been downloaded.

Have other Thunderbird users had this problem?

**Comment by eyalroz** [comment]
This is not a bug related to my extension. Please ask on Mozilla IRC/Matrix groups, or on bugzilla.mozilla.org
