### ISSUE TITLE
search in multiple folders (request)

### ISSUE THREAD

**Issue by ro-bi-no** [eyalroz/removedupes#238]
I've got a lot of messages in the send folder that are already in a few specific folders. I need to know if there's a duplicate of the original in one of those folders.
Or, to put it another way, I need to know if every message in the send folder was already stored in its destination folder so I can remove it from the send folder.
tks!

**Comment by eyalroz** [comment]
Search in multiple folders is supported. You just need to select those folders... unfortunately, the powers that be of the Thunderbird project have decided that users don't need to be able to select multiple folders, and have shipped versions which don't support such selection. See discussion here:

https://www.reddit.com/r/Thunderbird/comments/159989q/tbird_115_cant_ctrlclick_folders_to_select/

As for the Sent folder - by default, the extension ignores it. To change this, change the Extension's preferences and uncheck "Skip Special Folders".

Finally, you have the option to mark one set of folders as the only folders with originals (this is available on the right-click context menu) and only search another set of folders for dupes.
