### ISSUE TITLE
Remove duplicate messages

### ISSUE THREAD

**Issue by oleg-snt** [eyalroz/removedupes#24]
Hey. Excellent software. Can you add a killer feature? Filter duplicates by message body using regular expression? One more condition. It would be just great. But I hope you have time for this. Regards, Oleg.

**Comment by eyalroz** [comment]
First - I actually don't have much time to work on features right now... :-(

But - can you elaborate on the feature you're asking for? Are you asking for an additional comparison criterion? Or perhaps something that happens after duplicate-sets are formed?

**Comment by oleg-snt** [comment]
Made a drawing. I hope this will make it clearer.
![FIX](https://user-images.githubusercontent.com/72714495/95785797-dd08f180-0cef-11eb-8740-ba0e2c09f060.jpg)

**Comment by eyalroz** [comment]
This does not make sense. A comparison criterion is something which has innumerably many values. Here you'll just have a "matches' or "doesn't match", i.e. two values. Do you mean you want to only look for dupes among messages whose bodies matches the regexp?

**Comment by oleg-snt** [comment]
Yes. I am using this for rss. There are many of the same messages. But I cannot delete by id - it is always different. I cannot delete by title - it will delete unnecessary ones. The only difference is the city in the message body. As far as I understand, regular expression is indispensable here. Plus it gives you limitless duplicate filtering functionality. This would be a really good solution for complex cases.

**Comment by oleg-snt** [comment]
Example 1:
DevOps Engineer (remote)

`Vacancy of the company: Agiloft

Created: 13.10.

Region: Berlin

Estimated level of monthly income: from 150,000 to 300,000 rubles.`

Example 2:
DevOps Engineer (remote)

`Vacancy of the company: Agiloft

Created: 13.10.

Region: London

Estimated level of monthly income: from 150,000 to 300,000 rubles.`

If you use a regular expression for a company it will probably work

**Comment by oleg-snt** [comment]
If you use a regular expression for a company it will probably work

**Comment by eyalroz** [comment]
Filtering messages by a regular expression is not what my extension is about. That's not a comparison criterion.

Please use [FiltaQuilla](https://github.com/RealRaven2000/FiltaQuilla), to move the messages you're interested in to another folder; I believe it should support regular expressions. then apply removedupes regularly.
