### ISSUE TITLE
Uncaught InternalError: too much recursion

### ISSUE THREAD

**Issue by benjcmin** [eyalroz/removedupes#26]
I'm getting this Uncaught InternalError: too much recursion. It's folder with quite a lof of mail ca. 40.000. But sometimes it also works.
Effect is, nothing happens, no duplicate window opens nor message no duplicates is shown

Uncaught InternalError: too much recursion
    stripAndSortAddresses chrome://removedupes/content/removedupes.js:409
    sillyHash chrome://removedupes/content/removedupes.js:519
    populateDupeSetsHash chrome://removedupes/content/removedupes.js:631
    processMessagesInCollectedFoldersPhase2 chrome://removedupes/content/removedupes.js:332
removedupes.js:409:28
    RegExpGlobalMatchOpt self-hosted:2033
    Symbol.match self-hosted:1997
    match self-hosted:2931
    stripAndSortAddresses chrome://removedupes/content/removedupes.js:409
    sillyHash chrome://removedupes/content/removedupes.js:519
    populateDupeSetsHash chrome://removedupes/content/removedupes.js:631
    next self-hosted:1099
    processMessagesInCollectedFoldersPhase2 chrome://removedupes/content/removedupes.js:332

**Comment by eyalroz** [comment]
This is very strange, because I don't use deep recursion for anything in my code. Which versions of TB and removedupes are you seeing this with? Also, can you reproduce this on a clean profile with only removedupes installed?

**Comment by benjcmin** [comment]
Using Thunderbird 78.4.0 (64-Bit) on MacOS 10.15.7, RemoveDupes Version 0.5. Remove Dupes is the only active AddOn. There are two deactivated add ons. 
It's sadly not 100% reproducable. It seems to depend on the the checked criteria if I use diffrent one it's working on the same folder. But after a few tries the same criteria seem to work, but I haven't tried that in a controlled manner, but I usually use the same criteria settings over again.

**Comment by eyalroz** [comment]
So, it seems like this is a Thunderbird bug in regular expression processing. See:

[Lazy regex throws 'Uncaught InternalError: too much recursion' if not matched](https://bugzilla.mozilla.org/show_bug.cgi?id=1665154)

What that means is that you'll need to downgrade to v68, or wait for the bug to be fixed :-(

**Comment by gjs---** [comment]
For me the error occurs only if both of the following options are selected:

* [x] Compare addresses stripped and sorted
* [x] Author ('From')

The other options I use (Recipients, CC, Message ID, Number of lines, Send time, Subject) don't seem to matter.  So a workaround is to turn off one one of the options above.

Using binary elimination on the folders mentioned in #28, I narrowed the problem down to eight messages.  Each one shows the error when placed in a folder containing no other messages.  What they have in common (aside from being junk mail) is that the username portion of the 'From' address is 16 characters or longer.

These 'From' addresses show the recursion error consistently:

```
From: Help with Disability Insurance<helpwithdisabilityinsurance@saffr.info>  (27 chars)
From: westernunionresponse@westernunion.com <westernunionresponse@westernunion.com>  (20)
From: Thinking Power Games<thinkingpowergames@shaylinst.info>  (18)
From: BetterCreditChecks<bettercreditchecks@oriorleg.info>  (18)
From: BestBuy Online Store<BestBuyOnlineStore@response.bestbuy.com>  (18)
From: Match Partner Offer<matchpartneroffer@kneepho.info>  (17)
```

These have exactly 16 character usernames, and show the error intermittently:
```
From: ReportsforCredit<reportsforcredit@misustf.info>  (16)
From: Energy Bill Advice<energybilladvice@burdowi.info>  (16)
```

These have a long username if you count both sides of the "+", but they do not show the error:
```
From: "Tom Williams" <notification+kjdmhd_wk7ui@facebookmail.com>  (25)
From: "Facebook" <notification+kjdmhd_wk7ui@facebookmail.com>  (25)
```

My first guess would be that the long usernames are overflowing a 16-character string variable or regex pattern or loop limit somewhere in the address stripping/sorting code, perhaps bollixing up a recursive sort algorithm?  Just speculating.

Hope this is useful.

**Comment by eyalroz** [comment]
I'll try to find time to look into the issue this week.

**Comment by eyalroz** [comment]
@gjs--- : Would you mind putting some of these problematic messages together in a TB mail folder, then sending me the mbox file (or however it is you hold them together)? Also, are these two options sufficient for the bug to trigger, or are they just necessary?

**Comment by gjs---** [comment]
@eyalroz -- In my tests, the two options are both necessary and sufficient.  Other options have no effect.  However, I do not know whether such addresses in 'Recipients' or 'CC List' would cause the problem.

I can put together a collection of messages.  Should I attach a file here, or is there a way to send it to you directly?

**Comment by eyalroz** [comment]
@gjs--- : Attach it here if you can (and if you don't mind those emails being made public); otherwise send it to me. Naturally I guarantee not to share the contents with anyone else.

**Comment by gjs---** [comment]
I am attaching "RemoveDups Recursion Tests.zip", which contains several mbox files and corresponding .msf files (which you can ignore if desired):
- "RemoveDups Recursion Tests" contains the eight messages which I found cause 
[RemoveDups Recursion Tests.zip](https://github.com/eyalroz/removedupes/files/5539910/RemoveDups.Recursion.Tests.zip)
recursion errors.
- The "RemoveDups Recursion L _nn_" files each contain two copies of one message, whose 'From' username has length _nn_.  Running Remove Duplicates on any of these folders, if successful, should quickly list one duplicate.

Today some of the messages with usernames longer than 16 characters are failing intermittently rather than every time.

**Comment by eyalroz** [comment]
@gjs---: I am now able to reproduce the issue with two copies of the message entitled "How was your shopping experience".

The failure occurs at:
```
headerString.match(gEmailRegExp);
```
with `headerString` being `BestBuy Online Store<BestBuyOnlineStore@response.bestbuy.com>` and  the regular expression being:
`"(?:\b|^)[a-z0-9!#$%&*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@" +      "(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?(?:\b|$)"

**Comment by eyalroz** [comment]
Filed [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1677315) against the common Thunderbird/Firefox code.

**Comment by gjs---** [comment]
@eyalroz -- Thank you for looking into this problem.

I spent some time testing the regular expression you mentioned, using Perl and the [Mozilla JS Demo page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match).  It seems to work correctly with all the addresses I listed, if I specify case-insensitive matching.

I noticed that apostrophe (') appears in the local (username) portion of the address only after the '.', but that's obviously not the problem here.

**Comment by eyalroz** [comment]
[removedupes_0.5.1b1_tbird.xpi.zip](https://github.com/eyalroz/removedupes/files/5556223/removedupes_0.5.1b1_tbird.xpi.zip)

@gjs---  and everyone else: Please try the attached version, with a possible workaround/fix.

**BE VERY CAREFUL** - always remember this extension deletes messages. Only try it on a folder with a few "throw-away" messages so that you don't accidentally delete something important.

**Comment by gjs---** [comment]
@eyalroz -- I'm setting up a careful test, but need to break for something else.  I hope to post results in a few hours.

**Comment by gjs---** [comment]
I did a test using copies of the two folders in which I originally found the problem addresses (a total of 1084 messages).

From the first pair of copies, I created a baseline by using the workaround.  I ran Remove Duplicates 0.5 with `[ ] Compare addresses stripped and sorted` **OFF** and `[x] Author ('From')` **ON**, removed the duplicates, and compacted the folders to delete the residue.

In the other pair of copies, I ran Remove Duplicates 0.5.1b1 with `[x] Compare addresses stripped and sorted` **ON** and `[x] Author ('From')` **ON**, removed the duplicates, and compacted the folders.

For each folder, the number of duplicates removed by each version was the same.  For each folder, the mbox files produced by the two versions were line-by-line identical.

So I'm calling the fix a success.

**Comment by eyalroz** [comment]
> For each folder, the number of duplicates removed by each version was the same. For each folder, the mbox files produced by the two versions were line-by-line identical.

Wait, but the number of removed dupes should generally not be the same. That is, `Foo Bar <foo@bar.com>` and `Foo <foo@bar.com>` should be removed when we compare stripped addresses, but should remain when comparing addresses as is. Are you sure your folder didn't have such pairs of messages?

**Comment by gjs---** [comment]
I'm not 100% certain.  However, all the duplicate messages I have seen were due to a single message listing my Email address (or a forwarded address) more than once in a To:, CC:, or BCC: list.  When the same message is sent to me more than once, the received text, including the unstripped addresses, is identical (possibly excepting some server cruft in the header).

Do you know an easy way to check for the case you describe?  I think I would have to manually edit some duplicates in an mbox file, which I could do tomorrow if you like.

**Comment by eyalroz** [comment]
>Do you know an easy way to check for the case you describe? 

Essentially - emails from the same address but with a different name, or emails with the same group of people in To or Cc, but in a different order. And comparing those using only the relevant address field (Author, To, etc.).

**Comment by gjs---** [comment]
I am attaching a hand-crafted mbox file containing six messages which are identical except for the format and/or order of Email addresses in _From:_, _To:_, and _CC:_.  For a regression test, run RemoveDuplicates with those fields selected (and others if desired).

- [x] `Compare addresses stripped and sorted` _ON_ should find that the messages are _all duplicates_.

- [ ] `Compare addresses stripped and sorted` _OFF_ should find _no duplicates_.

This is meant as a quick check.  The addresses and variations are pretty simple, so it is not a stringent test of the pattern matching.

It works for RemoveDupes 0.5.1b1 on my PC with Windows 10 1903 and Thunderbird 78.4.3.  I have not rolled back to 0.5 to see whether it reveals the recursion problem.

[Non-Identical-Duplicates.zip](https://github.com/eyalroz/removedupes/files/5570332/Non-Identical-Duplicates.zip)

**Comment by eyalroz** [comment]
Thanks, @gjs--- . I guess this should be enough to push a new version to addons.mozilla.org.

**Comment by gjs---** [comment]
@eyalroz -- Sounds good.  Thank you for the fix.

**Comment by benjcmin** [comment]
Hi guys,
thx for having this deep look into this issue. Just was able to try the the version you provided here and it also seems to work for me. With that version no "Uncaught InternalError: too much recursion" occured again.
Thx for the support.
