### ISSUE TITLE
skipping special folders seems to be hard coded

### ISSUE THREAD

**Issue by HfPoe** [eyalroz/removedupes#27]
Setting extensions.removedupes.skip_special_folders to false does not seem to have an effect on removedupe's behavior.

![image](https://user-images.githubusercontent.com/74136025/98462883-bd160200-21b7-11eb-9c92-01e9cb771986.png)

![image](https://user-images.githubusercontent.com/74136025/98462909-f0f12780-21b7-11eb-9fe2-de16c918f6db.png)

![image](https://user-images.githubusercontent.com/74136025/98462929-13834080-21b8-11eb-98d8-8fc371108829.png)

The reaction is the same as with extensions.removedupes.skip_special_folders = true

Regards
Heribert

**Comment by eyalroz** [comment]
I'll try to look into this, this week. Please "ping"me if I don't reply.

**Comment by eyalroz** [comment]
I just checked this here and it seems to work fine. Also, the Inbox is not supposed to be skipped regardless of this setting - it's an exception to the rule.

Can you give _exact_ reproduction instructions for this issue?

**Comment by eyalroz** [comment]
Reporter, please reopen if/when you can give exact reproduction instructions.
