### ISSUE TITLE
The extension is incompatible with Thunderbird versions 78 and later

### ISSUE THREAD

**Issue by gkarag** [eyalroz/removedupes#3]
When I upgraded TB to v78 (currently 78.0.1), it disabled the extension and showed a warning message "Remove Duplicate Messages (Alternate) is incompatible with Thunderbird 78.0.1.". I use TB on macOS 10.14 in case it matters.

Thanks for your work!

**Comment by eyalroz** [comment]
Yes, it is incompatible. TB 78 completely removed support for XUL-based extensions. I will have to rewrite a lot of the extension to achieve compatibility again - and it will take some time.

**Comment by eyalroz** [comment]
@gkarag : See the new beta release.

**Comment by eyalroz** [comment]
Closed in favor of the milestone
