### ISSUE TITLE
Request: Remove duplicates across accounts

### ISSUE THREAD

**Issue by AleXSR700** [eyalroz/removedupes#30]
Hello everybody,
I love this add-on and I even installed Thunderbird after switching to Outlook because I missed this add-on. And no, I am not lying. Why I moved to Outlook? it is mandatory at work and sooner or later you don't want to use two programs anymore.

Anyway, I have found that I have quite a few duplicates from backups, mailbox problems etc. But they are spread across 4 different accounts. Would it be possible to have this add-on looked in all accounts synced in Thunderbird? The data is on the computer anyway. And all work individually. But I do not like the idea of having to download all messages from all accounts to my local folder, then search for duplicates and then having to re-upload all mails to all accounts (This is how I lost quite a few mails a few years ago).

Any help would be very much appreciated.

Thank you very much and best regards
Alex

**Comment by eyalroz** [comment]
It's not everybody - just me (@eyalroz )...

Anyway, you can already select multiple folders in Thunderbird and apply the dupe search to all of them. Just use Ctrl+Click to add to your selection.

**Comment by AleXSR700** [comment]
Hello @eyalroz ,

Then I truly thank you! This is awesome.

I tried selecting multiple accounts before but nothing happened. I do not get a "No duplicates found" and no search result. It just does nothing, so I figured it probably does not work.
Is there a way to debug and see why nothing is happending? It works on each of the mailboxes when I select them individually.

**Comment by eyalroz** [comment]
Do you also experience this with multiple _folders_ in different accounts rather than multiple accounts?

Also, what happens when you relax the comparison criteria? Please relax them gradually until none remain or until you start getting dupes.

If you get no dupes even with no comparison criteria, please navigate to `Tools > Developer Tools > Error Console` on the menus.

**Comment by eyalroz** [comment]
Please reopen when you can answer my questions...

**Comment by mfouesneau** [comment]
Dear All, I'm discovering this extension, and it sounds great. 
I cannot manage to find duplicates across accounts. If I select the inbox of account 1 and inbox of account 2 (and I know there are duplicates), it finds nothing...

(I removed the skip special folders)

**Comment by eyalroz** [comment]
@mfouesneau : Please open a separate issue.
