### ISSUE TITLE
Wrong link from Thunderbird documentation

### ISSUE THREAD

**Issue by danmichaelo** [eyalroz/removedupes#31]
Thanks a lot for making this extension, just left a [positive review](https://addons.thunderbird.net/nb-NO/thunderbird/addon/removedupes/reviews/1164671/)!

Just wanted to let you know that the two links on https://addons.thunderbird.net/nb-NO/thunderbird/addon/removedupes/ in the sentence *"(As Thunderbird is undergoing massive changes under the hood, always check out the releases page on the website's homepage for a beta supporting the latest Thunderbird version. You are also welcome to report issues.)"* goes to another extension (bidimailui).

Also, it seems like many of the negative reviews are from users who haven't read the documentation. Perhaps it could help to add a very visible link to the FAQ at the top of that page?

**Comment by eyalroz** [comment]
Fixed. Will consider adding a link to the FAQ at the top of the page. Thanks :-)

**Comment by eyalroz** [comment]
Fixed. Will consider adding a link to the FAQ at the top of the page. Thanks :-)
