### ISSUE TITLE
No dupes found, no filteirng criteria.

### ISSUE THREAD

**Issue by jtagcat** [eyalroz/removedupes#32]
I have non-exact match items, but for example the subjects and date match.

https://addons.thunderbird.net/en-US/thunderbird/addon/remove-duplicates had a separate dialogue for changing the duplicate criteria options.

Right now, I have everything duplicated :/

**Comment by eyalroz** [comment]
You can change the comparison criteria using either the menu-button on the main toolbar, or using the menus - Tools | Add-On Options | Remove Duplicate Messages.

**Comment by jtagcat** [comment]
Thunderbird by default doesn't offer that.

It's now only accessible via the hidden top menu.

**Comment by eyalroz** [comment]
If you're annoyed by the menu bar being off by default, please write:

alessandro@thunderbird.net

and ask him to enable it by default. Please CC me as well.

There have been numerous problematic UI choises in TB over the past several years, for sure.

**Comment by jtagcat** [comment]
I like it off, and I forget that legacy things are there, sorry.
