### ISSUE TITLE
No more duplicated emails found

### ISSUE THREAD

**Issue by dpieroux** [eyalroz/removedupes#33]
Hello Eyal,

I have been using your plugin for months with great satisfaction. But recently (I don't know exactly when, maybe about 2 weeks ago), it stopped finding any duplicate message. Typically, I've got :
  - mails sent to me and to a mailing list I belong to,
  - mails I send to a mailing list that I also belong to.

Before, these duplicates were all found.

Here are the configs I use (the first 2 are not managed by me, this is why they are not the latest version of TB):
ThB 60.2.1 64b / Linux / Plugin 0.4.1
ThB 78.5.0 32b / Win10 / Plugin 0.5.1b2 
ThB 78.5.1 32b / Win10 / Plugin 0.5.1b2

For the Win10 configs, our IT department asked us to enable the option "security.tls.version.enable-deprecated".  For the rest, I think that we are using a standard config.

Of course, I can provide you with any other information that you would need. 

Cheers,
Didier Pieroux

**Comment by eyalroz** [comment]
Are you sure the messages don't have subtle differences which you're ignoring but the add-on doesn't? e.g. extra white-space resulting in different numbers of lines?

What happens when you gradually drop comparison criteria? Do you eventually start seeing dupes?

**Comment by dpieroux** [comment]
> Are you sure the messages don't have subtle differences which you're ignoring but the add-on doesn't? e.g. extra white-space resulting in different numbers of lines?
> 
> What happens when you gradually drop comparison criteria? Do you eventually start seeing dupes?

Hello Eyal, Thank you for your immediate answer.

I did play with the options, and indeed, dupes starting to appear. 

So, you were right, the body of the duplicated messages are actually different, despite they look identical when displayed by Thunderbird. I saw differences by viewing the message sources. The root cause for the change of behaviour 2/3 weeks ago is probably linked to a change of HW or SW configuration of our institute email servers.

Anyway, everything is back in order, and your plug-in works as intended. Please accept my deepest apologies for this erroneous bug report!

Kind regards,
Didier P.

**Comment by eyalroz** [comment]
No apology necessary, it's all fine.

Of course - you can always consider following the Sponsor link at the top of the page and contribute to the continued support and development of this add-on :-)

**Comment by dpieroux** [comment]
> Anyway - if you like, you could consider following the Sponsor link at the top of the page and contribute to the continued support and development of this add-on :-)

Sure, you really deserve it! I use your add-on every day, it is very useful! 

Keep going ;)
Didier P.
