### ISSUE TITLE
Deleting Duplicates Doesn't work

### ISSUE THREAD

**Issue by psyscope** [eyalroz/removedupes#34]
When I tell it to delete duplicates by moving it to the trash folder, it actually moves it to the Local Trash folder. Emails are then not deleted and get redownloaded. Even though I told Thunderbird where the trash bin was.

**Comment by eyalroz** [comment]
The extension has nothing to do with message downloading or re-downloading.

What exactly is the extension not doing that it's supposed to do? From your description it seems like the messages are moved to the trash folder like they're supposed to.

**Comment by psyscope** [comment]
But it should be moving them to the server folder of each email account the
duplicate is found. How is it different from what it is doing now? It moves
them to a local folder. The emails aren't actually deleted, so thunderbird
will check online and see the same emails and redownload them.

**Comment by eyalroz** [comment]
> But it should be moving them to the server folder of each email account the duplicate is found.

Ah. this is interesting. You're saying you're searching for dupes in folders from different accounts, and you want different dupes to be put in different Trash folders.

Or - are you complaining about how, even for a single account, the default chosen Trash folder is not that account's Trash folder?

**Comment by filipposfilippides** [comment]
Problem with many same emails 
It doesn't find any duplicates

![Screenshot_20210104_082242](https://user-images.githubusercontent.com/27666059/103506773-35bad700-4e66-11eb-9fdd-983dfd4a43ef.png)

**Comment by eyalroz** [comment]
Closed due to lack of reporter responsiveness. Feel free to reopen when you have an answer.
