### ISSUE TITLE
Is the add-on supported on TB daily (86.0a1) / Linux 5.10 /Ubuntu 20.10 ?

### ISSUE THREAD

**Issue by clochrua** [eyalroz/removedupes#35]
Add-on installs on daily without problem But:
1. If TB is restarted add-on's ICON (in top RH corner) is not shown and no entries in tools menu. Diable and re-enable the add-on and the icon appears and tools menu has entries for "Remove Duplicates"
2. Add-on finds and marks all duplicate files in folder but the delete does nothing and error message displayed "Failed erasing messages" 
js console log attached 
[console-export-2020-12-30_21-26-58.txt](https://github.com/eyalroz/removedupes/files/5756146/console-export-2020-12-30_21-26-58.txt)

**Comment by eyalroz** [comment]
I don't actively support TB dailies - I just don't have the time for that, especially with fundamental changes occurring routinely over the past couple of years. Please reopen this bug if this happens in a beta of an intended release.

Sorry :-(

**Comment by clochrua** [comment]
Thanks for the quick reply and no sorry needed, I quite understand.
Rgds
Bill

On 31 December 2020 14:03:23 CET, Eyal Rozenberg <notifications@github.com> wrote:
>I don't actively support TB dailies - I just don't have the time for
>that, especially with fundamental changes occurring routinely over the
>past couple of years. Please reopen this bug if this happens in a beta
>of an intended release.
>
>Sorry :-(
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/eyalroz/removedupes/issues/35#issuecomment-752953851

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
