### ISSUE TITLE
cannot find duplicates 

### ISSUE THREAD

**Issue by filipposfilippides** [eyalroz/removedupes#36]
[2008.zip](https://github.com/eyalroz/removedupes/files/5763313/2008.zip)

Problem with many same emails 
It doesn't find any duplicates

After changing criteria, removing messageid, it found some but not all.
EDIT: WORKED!
Author, Recipient, Time(in secs), Subject

![Screenshot_20210104_082242](https://user-images.githubusercontent.com/27666059/103506773-35bad700-4e66-11eb-9fdd-983dfd4a43ef.png)

**Comment by eyalroz** [comment]
So, can I close this issue, if you've found dupes? Note that there might be "near-dupes", which differ due to an extra empty line, or a few seconds send time difference etc.

**Comment by filipposfilippides** [comment]
> So, can I close this issue, if you've found dupes? Note that there might be "near-dupes", which differ due to an extra empty line, or a few seconds send time difference etc.

Yes, that was. Near-dupes!
Of course! Thank you for this valuable tool. Have a happy new year.
Filippos
