### ISSUE TITLE
0.4 suiterunner not working properly with SeaMonkey 2.53.5.1 x64 linux

### ISSUE THREAD

**Issue by dhdurgee** [eyalroz/removedupes#38]
As suggested I installed 0.4.1 suiterunner on my SeaMonkey 2.53.5.1 x64 linux here.  After a restart I now have the "Remove duplicates..." menu item on my mail folders.  When I try to use it I am seeing inconsistent results. On some I see some quick status messages and then a pop-up window "No duplicates found." On others I see a final status message "Duplicate message search complete." but no pop-up window of any kind.  These are the folders I suspect I have duplicates in.  One of these has 34280 messages and the other has 13441 messages.  Both of these are for POP accounts. Can I get this to work? Dave

**Comment by dhdurgee** [comment]
Is there any debug flag I can set or other way to provide you with what you would need to know to correct whatever is preventing this add-on from working?  Do you create a log anywhere I can provide you? Is there any reason to think an earlier version would work for me?

**Comment by eyalroz** [comment]
The debug flags are compile-time only, they don't exist in the distributed XPI. If you download the source, you can build an XPI with debugging code enabled.

I'll also mention again that SM is not actively supported; it's a "it used to work" kind of thing.

Anyway, for the first case - you probably had "near-duplicates" which still differed by some minor detail, e.g. extra whitespace line.

For both cases - it's possible something failed; check the error console for entries with "removedupes" in them.

**Comment by dhdurgee** [comment]
The error console shows nothing for "removedupes" which is unexpected 
given the behavior.

I could download the source, but I am not sure that I have what is 
needed to build it.  Is the documentation for building from source included?

You saying "it used to work" leads me to ask at what release level?  
Perhaps I should try an earlier known-to-have-worked one before I 
attempt to debug the current release.  If an earlier release works I get 
my dupes removed and you get information that might enable you to narrow 
down where the current release is failing for SM.

Dave

**Comment by eyalroz** [comment]
> You saying "it used to work" leads me to ask at what release level? 

I last tested before 0.4, I don't even remember...

The source should build on a typical Unix environment, with the common shell tools available (cat, zip, cut, stuff like that), and also with perl installed. It doesn't have to be a recent version of perl. There's a build script written in bash.

**Comment by eyalroz** [comment]
Please contact me via email if you're continuing work on this and require any additional information/assistance.
