### ISSUE TITLE
your programme did not find any duplicates

### ISSUE THREAD

**Issue by KarlSchwinginsfeld** [eyalroz/removedupes#39]
Hello Eyal, 
.
Unfortunately, your programme did not find any duplicates, although I even duplicated another e-mail to be sure.
<img width="323" alt="Bildschirmfoto 2021-01-07 um 23 14 57" src="https://user-images.githubusercontent.com/77128462/103952168-3abaa780-5140-11eb-9d49-3787ef9c00c6.png">
<img width="698" alt="Bildschirmfoto 2021-01-07 um 23 27 42" src="https://user-images.githubusercontent.com/77128462/103952171-3b533e00-5140-11eb-8ca4-e2f98a20567e.png">
<img width="1065" alt="Bildschirmfoto 2021-01-07 um 23 27 31" src="https://user-images.githubusercontent.com/77128462/103952174-3c846b00-5140-11eb-8144-e1008c28bea2.png">
<img width="792" alt="Bildschirmfoto 2021-01-07 um 23 26 35" src="https://user-images.githubusercontent.com/77128462/103952177-3d1d0180-5140-11eb-860e-b1329c07d968.png">
.
How can I install your beta version? 
. 
Best regards  
.
Michael.Wingenfeld@aufstellen.Online
.

**Comment by eyalroz** [comment]
This is likely because the supposed-duplicate is only a near-duplicate, as far as TB is concerned. This typically happens if there's an extra empty line(s), or if the send time is off by a few second etc. Can you please check by gradually removing some of the comparison criteria?

You can control them using the Add-On's options, available through the main menu; or using the removedupes toolbar button drop-down menu.

**Comment by KarlSchwinginsfeld** [comment]
Hello Eyal, 

. 

Thank you for your quick and helpful reply. I took out some comparison criteria and now it works.

.

Thank you and best regards

.

Michael

.

 

Von: Eyal Rozenberg <notifications@github.com>
Antworten an: eyalroz/removedupes <reply@reply.github.com>
Datum: Freitag, 8. Januar 2021 um 11:35
An: eyalroz/removedupes <removedupes@noreply.github.com>
Cc: KarlSchwinginsfeld <Schwinginsfeld@web.de>, Author <author@noreply.github.com>
Betreff: Re: [eyalroz/removedupes] your programme did not find any duplicates (#39)

 

This is likely because the supposed-duplicate is only a near-duplicate, as far as TB is concerned. This typically happens if there's an extra empty line(s), or if the send time is off by a few second etc. Can you please check by gradually removing some of the comparison criteria?

You can control them using the Add-On's options, available through the main menu; or using the removedupes toolbar button drop-down menu.
