### ISSUE TITLE
Full access to anything on my computer ?!?

### ISSUE THREAD

**Issue by Nick222** [eyalroz/removedupes#46]
Why this addon installation requires full access to anything on my computer ?!?

**Comment by eyalroz** [comment]
I'm not sure what you mean. Any regular add-on to Thunderbird has the same privileges as Thunderbird, which are the same privileges as any other application you run, which are _your_ privileges as a user. If you can do it, then any application you run can do it.

**Comment by Nick222** [comment]
> Any regular add-on to Thunderbird has the same privileges as Thunderbird
No - it is not. See https://support.mozilla.org/ru/kb/permission-request-messages-thunderbird-extensions

**Comment by eyalroz** [comment]
> > Any regular add-on to Thunderbird has the same privileges as Thunderbird
> 
> No - it is not. See https://support.mozilla.org/ru/kb/permission-request-messages-thunderbird-extensions

That does not contradict what I said. But that does illustrate the pressure that the TB council is putting on users and authors to drop regular extensions and restrict ourselves to "web extensions". That is an ongoing struggle (which sometimes gets quite dirty politically). As part of it, we get a scare message before installation.

At any rate, the code is right here, so you could - if you like - verify that the only thing the extension accesses is messages in mail folders.
