### ISSUE TITLE
Cannot download extension

### ISSUE THREAD

**Issue by mgarofano80** [eyalroz/removedupes#47]
Hi! It looks like Thunderbird is no longer hosting the link to download your extension. Could you please offer an alternate location ?

**Comment by eyalroz** [comment]
The extension is still available from:

https://addons.thunderbird.net/en-US/thunderbird/addon/removedupes/

I'm not sure what you mean by "no longer hosting".

Regardless, this repository has a "Releases" section which you can download from:

https://github.com/eyalroz/removedupes/releases

**Comment by mgarofano80** [comment]
Thank you for much, I was getting a page not found error, not anymore.
