### ISSUE TITLE
Support for Thunderbird 89.x

### ISSUE THREAD

**Issue by AJ** [eyalroz/removedupes#48]
Hello,

I've installed the addon to my thunderbird (V89.0b1, 64bit) running on Windows 10 pro.
But now, I'm unable to find either the button to add to Thunderbird or find the context menu option. Both of them are not showing up:

![Screenshot 2021-04-24 143630](https://user-images.githubusercontent.com/6901/115953679-7f5d2980-a50a-11eb-9405-5b180442c7c8.png)

What do I do now to use the extension?

Thank you

**Comment by eyalroz** [comment]
The extension does not currently support TB 89... I would guess it appears as being disabled in the Add-Ons dialog. I hope to get around to updating the extension to support the new version over the next month or two. Please ping me again in a month if I haven't done so...

**Comment by AJ** [comment]
Thank you for the update. I'll wait for it :)
The Add-Ons dialog does not list it as disabled. I can even go into the "Manage" dialog for the extension

**Comment by eyalroz** [comment]
Do you get anything in the error console that mentions "removedupes"?

**Comment by AJ** [comment]
If I click on "Manage" in the addons pane, I get this in the error console:

NS_ERROR_NOT_AVAILABLE: 2 ActivityManager.jsm:129
    getActivity resource://gre/modules/ActivityManager.jsm:129
    removeActivity resource://gre/modules/ActivityManager.jsm:82
    onFolderRemovedFromQ resource:///modules/activity/autosync.jsm:247
    _timerCallback resource:///modules/AppIdleManager.jsm:30

On restarting TB, I get the errors as displayed in the attachment. None of them mention removedupes but 2 of the errors are related to extensions. So I'm not sure

![tbird-error-console](https://user-images.githubusercontent.com/6901/115955704-d6b4c700-a515-11eb-932a-8b5e831323f3.png)

**Comment by eyalroz** [comment]
That's the attempt to load my extension. The UUID code is mine.

**Comment by AJ** [comment]
@eyalroz Just a reminder as mentioned by you. Did you have a chance to look at updates to support newer TB versions?

**Comment by mcarlson** [comment]
I would love it if you could update this - I really really miss it!

**Comment by eyalroz** [comment]
Please try the new beta release:

https://github.com/eyalroz/removedupes/releases/tag/v0.5.2b1

It _should_ work with TB 0.90b3.

**Comment by eyalroz** [comment]
There's now a second beta release, compatible with TB 91.
