### ISSUE TITLE
Never finds any duplicates

### ISSUE THREAD

**Issue by ChiefHart** [eyalroz/removedupes#50]
This add on never finds any duplicates when there are some in my In box.  At this rate I  could delete manually and forget this add on....
Why can it not find the obvious duplicate emails in my In box???
I am using TB 77.7.1, FF 88.0
POP!_OS 20.04LTS

![Selection_024](https://user-images.githubusercontent.com/45080732/117382807-5135fd00-aead-11eb-9fee-6a71642eb169.png)

**Comment by eyalroz** [comment]
This is most likely because your messages are nearly-duplicate but not quite duplicate. For example: An extra newline at the end of the message. Start gradually removing comparison criteria until you see duplicates, then add criteria back to get at the exact combination that works for you.

**Comment by eyalroz** [comment]
Closing for now; if my suggestion did not help, you may reopen and add more details.

**Comment by ThongSong7** [comment]
This helped me quite a bit!  I was able to do what you requested and found where the 'duplicates' were found - Thank you!
