### ISSUE TITLE
no right click search window

### ISSUE THREAD

**Issue by TheCuteDuke** [eyalroz/removedupes#52]
dear eyal,
I want to use Thunderbird and removedupes to clean up my migrated Exchange 365 Account.
But it doesn't work anyway...
right click on the folder - click on remove duplicates - nothing happens...

kind regards 
Oliver

**Comment by eyalroz** [comment]
1. What version of Thunderbird are you using?
2. Do you get a message saying "No duplicates found"?
3. Do you get any removedupes-related errors in the error console?

**Comment by eyalroz** [comment]
Feel free to reopen if you can answer my questions.
