### ISSUE TITLE
No Icon

### ISSUE THREAD

**Issue by Williepo** [eyalroz/removedupes#53]
Thunderbird 78.10.2 (64bit)
Installed remove dupes add on.  Appears in addon list.
Restarted TBird.  No icon on icon bar so cannot set up conditions or run it.

**Comment by eyalroz** [comment]
Well, let's start with a workaround: 

* Enable the menu bar
* On the menu, navigate to Tools | Add-On Options | Remove Duplicate Messages
* The configuration dialog will come up; you can now set the comparison criteria and other settings as well

**Comment by eyalroz** [comment]
I use the same version of TB as you, and I don't see this issue. So,

1. Please try it with a clean new profile and check whether you still experience the same issue.
2. Check the Error Console for entries mentioning "removedupes".

**Comment by ricounet67** [comment]
I have the same issue: no icon available to add in the toolbar and no command.
So the add-on seems to be installed but I am unable to launch it. The options are available.

I am running Thunderbird beta 90 and it is the same since I switched to the beta channel

**Comment by eyalroz** [comment]
@ricounet67 : Thunderbird 90 is not supported (yet); the extension doesn't load in TB 89 or later. So, what you're describing is a different issue.
