### ISSUE TITLE
Failed to move to trash

### ISSUE THREAD

**Issue by mostly-nonsense** [eyalroz/removedupes#60]
Receiving failed moving messages error.

Failed moving messages to: 
imap://xxx%40xxx@imap.gmail.com/[Gmail]/Trash
&
mailbox://nobody@Local%20Folders/Trash

Thunderbird: 78.12.0 (32-bit)
Version: 0.5.2b2

**Comment by eyalroz** [comment]
This is a dupe of #57 . Please use the build available there (0.5.2b3)
