### ISSUE TITLE
Add-on 0.5.2b2 and 0.5.2b3 don't work in TB 78.12.0 (64-bit)

### ISSUE THREAD

**Issue by JohnAnderson** [eyalroz/removedupes#62]
I've been trying to use the add-on for a while now, and it just doesn't work.  The context menu entry appears in the right-click popup, but nothing happens when it's clicked.  This is the case for both versions 0.5.2b3 and 0.5.2b2.  Here is the most recent error console entry for 0.5.2b3:

![removedupes error Screenshot 2021-08-04 113424](https://user-images.githubusercontent.com/4228382/128210505-e08b504f-d3a1-4a7a-8f75-2491ab8291ee.jpg)

I'm transitioning from Outlook to TB, and need to merge very large email folders, so removing duplicates is extremely important.  Yours seems to be the only TB add-on for this that is compatible with TB 78, so I would appreciate any help you could provide.

Thanks

**Comment by eyalroz** [comment]
Well, first, try [version 0.5.1](https://github.com/eyalroz/removedupes/releases/tag/v0.5.1b2), which should still work.

Now, please tell me:

* Which OS
* Which exact version of TB are you using?
* Are you getting any other error or warning message?
*

**Comment by JohnAnderson** [comment]
Not sure if this message will get posted as I'm not familiar with github functionality and closed the issue when I thought I was closing a reply to your comment.  Can the issue be opened again? (Oh, I think I see how to do that now.)

To answer your questions:
- OS is Windows 10 Pro 21H1
- Exact version of TB is 78.12.0 64-bit:
![image](https://user-images.githubusercontent.com/4228382/128215303-8f98638d-23fa-4f78-9e67-61a5df7e7e79.png)
- No other errors or warnings.  When I click on Remove Duplicates in the context menu, the context menu goes away, but nothing else happens at all.

Thanks for the quick reply.

**Comment by JohnAnderson** [comment]
I will try that other version later today. Thanks again.

John E Anderson, PhD
@doctorjah
Associate Lecturer Emeritus of Physics, University of North Florida
Founder, Science-Culture-Future Project  #ScienceCultureFuture
Executive Director, Jacksonville Joe Berg Seminars
+1-781-816-9164
Sent from my iPhone

On Aug 4, 2021, at 12:01, Eyal Rozenberg ***@***.***> wrote:

﻿

Well, first, try version 0.5.1<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Feyalroz%2Fremovedupes%2Freleases%2Ftag%2Fv0.5.1b2&data=04%7C01%7Cjeanders%40unf.edu%7Cb1c0146de467459c466c08d95760e2a7%7Cdf29b2fa8929482f9dbb60ff4df224c4%7C1%7C0%7C637636896674508975%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yK5hBIlMX4KBYvIj%2FWoat%2FJUI7CSMq%2FZSSfsPZcGRus%3D&reserved=0>, which should still work.

Now, please tell me:

  *   Which OS
  *   Which exact version of TB are you using?
  *   Are you getting any other error or warning message?
  *

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Feyalroz%2Fremovedupes%2Fissues%2F62%23issuecomment-892778251&data=04%7C01%7Cjeanders%40unf.edu%7Cb1c0146de467459c466c08d95760e2a7%7Cdf29b2fa8929482f9dbb60ff4df224c4%7C1%7C0%7C637636896674518974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iheHsiZJ8lNc6zL%2BJM0yKvJVOA09PidJlE3Oj5vHWg0%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABAIKHTKVPJ7UJYQL3FOJWTT3FPXHANCNFSM5BROHPPA&data=04%7C01%7Cjeanders%40unf.edu%7Cb1c0146de467459c466c08d95760e2a7%7Cdf29b2fa8929482f9dbb60ff4df224c4%7C1%7C0%7C637636896674528971%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AXe3tXm0YHQbMvbewl2L3%2FjiZZrW5lT1AbbU%2BPinwNQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjeanders%40unf.edu%7Cb1c0146de467459c466c08d95760e2a7%7Cdf29b2fa8929482f9dbb60ff4df224c4%7C1%7C0%7C637636896674528971%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0n%2FhUW2PqjEwkvvAzfFtdl%2Fh9U3rk45LT2QbuCHXJN4%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cjeanders%40unf.edu%7Cb1c0146de467459c466c08d95760e2a7%7Cdf29b2fa8929482f9dbb60ff4df224c4%7C1%7C0%7C637636896674538964%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eeAxI3LltB6JXXhMBHIkNwFANSRQM5%2FAZ3qScR3ZI%2BI%3D&reserved=0>.

**Comment by eyalroz** [comment]
Hello John,

Please don't directly reply to GitHub comment notification emails. Or rather - if you do, please don't quote anything, since then we get an absolute mess here on the page.

**Comment by JohnAnderson** [comment]
Sorry. I noticed that. Won’t use email again.

**Comment by JohnAnderson** [comment]
Hello again.  v0.5.1b2 has no XPI file for installation into TB.  Can one be made from the source files on the site?

**Comment by eyalroz** [comment]
@JohnAnderson : It's on addons.thunderbird.net. i.e. [here](https://addons.thunderbird.net/en-US/developers/addon/removedupes/versions/2474861).

**Comment by JohnAnderson** [comment]
That worked.  Thanks so much!  Not sure why the newer versions weren't working for me...

**Comment by eyalroz** [comment]
Please try this new version:

https://github.com/eyalroz/removedupes/releases/tag/v0.5.2b4

**Comment by truthsword** [comment]
> Please try this new version:

5.2b4 resolved this for me. With b3, I had no response after initiating duplicate search.

Win10 Home 20H2
TBird: 78.12.0 64-bit

**Comment by JohnAnderson** [comment]
That worked for me, too.  Thanks!

Win10 Pro 21H1
TB 78.12.0 64bit
