### ISSUE TITLE
Match quoted header fields too

### ISSUE THREAD

**Issue by romainhk** [eyalroz/removedupes#68]
I've recently use this module over large set of mails with duplicates (thank you for this useful module by the way :), and I've noticed that same emails but with a "quoted header field", are not recognized has duplicates.
For instance, you can have one with `To: Someone <someone@nowhere.org>` and another `To: 'Someone' <someone@nowhere.org>`.

Maybe you could extend the matching algorithm to include this quoted values ?

**Comment by eyalroz** [comment]
Have you tried the "Compare addresses stripped and sorted" option?

**Comment by romainhk** [comment]
I haven't seen that option ! Apparently, it does the trick for a part of my duplicates :)
Thanks !
