### ISSUE TITLE
Does not find duplicates that exist

### ISSUE THREAD

**Issue by zahroc** [eyalroz/removedupes#69]
Not finding duplicates. There are multiple duplicates within the folder for testing purposes and it does not find any
I have attached a screenshot of the exact two messages within the folder that are the same.
Thunderbird v91.1.1
Windows 10 21H1
![image](https://user-images.githubusercontent.com/41906902/134219995-a409396e-73aa-4ea1-86fb-c99dc78c03f4.png)

**Comment by eyalroz** [comment]
The messages are probably nearly-duplicate rather than proper duplicates. For example: They may differ by an extra newline at the end. Please remove comparison criteria until they start showing up as dupes.

**Comment by Jurgster** [comment]
I found an insert from the AV program stating the e-mail as clean in one version of the e-mail and the other it is not flaged.

X-Antivirus: Avast (VPS 211008-0, 8.10.2021), Inbound message
X-Antivirus-Status: Clean

there is the suggestion, cut out AV flags for comparison.

**Comment by eyalroz** [comment]
@Jurgster : I should also mention that I have to "err on the side of caution", since it's always better to keep some almost-dupes than to accidentally delete something the user didn't really want deleted.
