### ISSUE TITLE
Not searching special folders

### ISSUE THREAD

**Issue by Grosfaaters** [eyalroz/removedupes#70]
I have a problem with duplicate messages in Sent folder. When trying search for duplicate messages on Sent, then pops-up window with message "Not searching special folders". How special is Sent folder and what does it mean? And what to do to avoid this message.
Thunderbird version 91.*

![image](https://user-images.githubusercontent.com/16088744/135824734-7b112be8-0ed2-4257-9112-c780812c7895.png)

**Comment by eyalroz** [comment]
You can enable searching special folders using the add-ons configuration dialog - which is accessible through the add-ons tab in TB 91.

"Special" folders are those which are used by TB for some special function: Storing messages after they've been sent; storing draft messages; storing deleted messages; etc. An exception is the Inbox folder, in which new messages are stored - it _is_ searched despite being kind-of a special folder.
