### ISSUE TITLE
does not recognise diplicates with different tags

### ISSUE THREAD

**Issue by hpvpp** [eyalroz/removedupes#75]
and still does not recognise those duplicates with all tags removed as below

see attacheds
[email one.txt](https://github.com/eyalroz/removedupes/files/7573791/email.one.txt)
[email two.txt](https://github.com/eyalroz/removedupes/files/7573795/email.two.txt)

**Comment by eyalroz** [comment]
To make it easier for me to reproduce the issue, can you create a mail folder in TB, copy these two messages there, then attach the raw file for that folder?

**Comment by eyalroz** [comment]
Feel free to reopen when you can accommodate my request. I'm not able to reproduce this.
