### ISSUE TITLE
Not finding duplicates

### ISSUE THREAD

**Issue by planalp** [eyalroz/removedupes#78]
It's just not finding duplicates.  I'm on 78.14, and need to stay there.  It does not even say no duplicates are found.  I have tried paring down the match criteria to the absolute minimum, but no luck.  I have tried disabling other add-ons to some degree, but not all of them - are there known conflicts?
thanks
Roy
"desperate in Durham"

**Comment by eyalroz** [comment]
> I'm on 78.14, and need to stay there.

That's not a problem, the extension supports that version. To the best of my knowledge anyway.

> It's just not finding duplicates.  It does not even say no duplicates are found.

Then perhaps there's some message in the Error Console? Please check. On the menus, it's under Tools | Developer Tools | Error Console. You'll see a lot of errors and warnings from TB itself, look for messages with "removedupes" in the filename.

> I have tried disabling other add-ons to some degree, but not all of them - are there known conflicts?

No, but theoretically there could be some kind of conflict.

**Comment by Keanu73** [comment]
Hi,

I'm on Thunderbird 91.4.1 and I was initially able to remove a bunch of duplicates, however, after removing/adding my account a bunch of times, it can no longer detect any more duplicates, even though when I was last able to remove duplicates, it said there were around ~2000 sets. I'm using the Beonex OWL extension with an Office 365 account for this, & I have double checked the Error Console and there is no output from your plugin in particular whatsoever.
