### ISSUE TITLE
Not searching special folders

### ISSUE THREAD

**Issue by coronaprint** [eyalroz/removedupes#79]
I have 1.092.446 messages in my “Archives” folder after migrating from Gmail to Infomaniak.
All my Gmail labels seems to be converted in folders, and one message seems to be duplicated in as many folders that it had labels for this unique email.
This Gmail account had a size of 78,95Gb and has now 266.4Gb in Infomaniak.

1. I installed Thunderbird v.68.12.1 (64-bit) on MacOS (12.3.1 (21E258)).
2. I moved all the emails from each folder to one unique folder, “Archives”.
3. I created a new account for this email address in Thunderbird.
4. I installed Remove Duplicate Messages (v.0.5.2b4).

After having all the messages downloaded from the mail server, I did a right-click on the “Archive” folder, but got the next message :
<img width="333" alt="2022-04-04_11-28-17" src="https://user-images.githubusercontent.com/102039104/161515543-91401108-d633-464c-9e37-397a29b5529e.png">

I already tried this on another MacBook Pro M1 with last Thunderbird version (91), but I also got the same error “Not searching special folders”. Since _Remove Duplicate Messages_ 0.5.2b4 shows “Works with Thunderbird 68.0”, I tried on version 68 as described above.

**Comment by eyalroz** [comment]
You can use the preferences dialog to enable searching special folders... in the prefs dialog, in the General Settings, uncheck "Skip Special Folders".

This is a safety precaution, since often people don't actually intend for dupes to be removed from special folders like 'Archive'.

**Comment by coronaprint** [comment]
Thank you @eyalroz for your answer !

I unchecked as you told me : 

![image](https://user-images.githubusercontent.com/102039104/161790704-b537733b-aa37-488d-bf4f-337a68e465f6.png)
![image](https://user-images.githubusercontent.com/102039104/161790747-2aa882a1-0922-4b6c-918d-77410ede7122.png)

And the duplicate search started then perfectly during a few hours.
After finishing the search, Thunderbird is working... yet since more than 12 hours : 
<img width="1316" alt="2022-04-05_17-30-47" src="https://user-images.githubusercontent.com/102039104/161792117-9a4532f7-cb9b-46f0-8a8f-8f4c0f41f529.png">

We'll see later what's happening...

**Comment by eyalroz** [comment]
> After finishing the search, Thunderbird is working... yet since more than 12 hours :

I'm not sure I understand. What indication did you get that the search was finished? Did the progress bar at the bottom count up to the number of messages you h ave? Did you see a review dialog come up?

I should mention that if there are tens of thousands of dupes or more, the review dialog might be too heavy for Thunderbird, and you may need to uncheck "Review search results", and simply let it move the results to trash or to another folder, and review yourself if you like.

Also, just to test things out, you could copy a small number of messages (say, 10,000) to a temporary local folder, perform a dupe search, and make sure it works.

The extension is limited by the "willingness" of Thunderbird to work with large numbers of messages, which is less than perfect.

**Comment by coronaprint** [comment]
Thank you @eyalroz for your help !!!
We just finished the cleaning.
Finally :
Last Thunderbird version (91.8.0 - 64-bit) on MacOS 12.3.1 (21E258)
After Thunderbird crash, I started all again with a new account profile, letting the 1.092.446 messages being downloaded : after a first lot of 40.000 emails dowloaded, I put TB offline, I start a "remove duplicates", restart TB, and download 40.000 emails more.
Doing so till all the emails were downloaded, the duplicates deleted, and the account synced, we have now 92Gb online in the Infomaniak webmail, instead of 266.4Gb.
We'll contribute to thank you for your support.
Best regards,
Nicolas

**Comment by Korb** [comment]
> All my Gmail labels seems to be converted in folders, and one message seems to be duplicated in as many folders that it had labels for this unique email.

Do I understand correctly that users of the Labels function in GMail in most cases need to enable the “Skip Special Folders (Sent, Drafts etc.)” item in the extension settings? I've been using GMail' tags since the late 2000s, but this is the first time I've heard that Labels are "Special Folders". Can you add a tooltip about this to the extension's settings interface? There, half of the window is empty, and there is room for a tip.
