### ISSUE TITLE
Is there any explanation for the "Set original message folders(s) for the next duplicate search"?

### ISSUE THREAD

**Issue by xpseudonym** [eyalroz/removedupes#82]
I don't like picking up old fags (a side issue to #17) , but I have the same question - how is this feature used?

**Comment by eyalroz** [comment]
It does what it says... but so as note to be facetious: 

Suppose I have folders F1 with messages m1, m1, m2 and F2 with messages m2, m3, m3, with messages . If I set only F1 as the folder with original copies, and search F1 and F2, I will detect the pair of m1's and the pair of m2.  If I set only F1 as the folder with original copies, and search F2, I will detect the pair of m2's only. If I don't set the originals folders and search F1 and F2, I will detect the pairs of all of m1, m2 and m3.

**Comment by xpseudonym** [comment]
Thank you.
M
