### ISSUE TITLE
disable confirmation prompt?

### ISSUE THREAD

**Issue by xpseudonym** [eyalroz/removedupes#83]
Is there any way to disable the confirmation prompt?

I disabled the 'Review search results before deletion' flag - but, I want the dup review, it's the idiot prompts that follow that I wish to avoid - one per dup and approx. 3500 of them...  I have a back up, so I'm happy to 'dive on in'.

**Comment by eyalroz** [comment]
@xpseudonym : I will absolutely not remove the confirmation prompt, and I would claim you don't really want to. It is much better to waste a little more time when deleting messages than to accidentally delete something permanently and then regret it. I would get people every day complaining about how they deleted messages from their loved ones, bank account credentials or what not. No way.

However... if you moved all of the dupes into the trash, then you would not get the confirmation prompt, and finally you could clear your trash just once.

**Comment by xpseudonym** [comment]
Ah ha!  The long way round is actually the short way round :smile: 
Many thanks.
M
