### ISSUE TITLE
Duplicate message not being detected - Feature request

### ISSUE THREAD

**Issue by ThorvaldAagaard** [eyalroz/removedupes#84]
I have some messages, where it seems it should be detected in the add-on

![image](https://user-images.githubusercontent.com/10560652/169660597-d494ca91-8342-4f69-a882-0a5059cc3b36.png)

Using these settings
![image](https://user-images.githubusercontent.com/10560652/169660617-298a7b4b-f03b-4fd8-b4fa-968e2de42829.png)

Now logically it must be the messageID that is different as Author and Send Time can be seen on the screen.

Running without comparing messageID gives a lot of duplicates, but I managed to find the above mails in the list
![image](https://user-images.githubusercontent.com/10560652/169660760-0859f3fa-7921-4c60-bb2e-f80e68c75260.png)

confirming my suspicion.

Now how the messageID can disappear I really have no idea about, but it would be nice if it was possible to match messageID with blank as a wildcard.

In other mail other of the comparable fields are missing, so an option allowing missing fields to be comparable (Missing is eaual any value) would be nice.

**Comment by eyalroz** [comment]
This is quite counter-intuitive. If one message is missing some header and the other isn't, then they aren't duplicates - they're different. If you want to ignore this difference, then - why not drop this as a criterion?

**Comment by ThorvaldAagaard** [comment]
If I drop this as a criteria I get a lot of other duplicates - I understand your concern, but missing attributes is often due to some errors in the mailsystem,

Currently we have true and false, and I am looking for a kind of Maybee :-)

But I will continue my manual process

**Comment by eyalroz** [comment]
I need to think about this. You see, while I understand that in your particular case this feature would have benefit, I have to weight it against the potential detriment of people mistakenly enabling this, then deleting some of their data unintentionally.

How prevalent is this phenomenon? I have not gotten complaints about this before.

**Comment by ThorvaldAagaard** [comment]
I think this only happens with old mail, where the import from other mail systems has left som missing attributes.

I can see in my mail box from 20 years old mail, that I have the same mail multiple times, sometimes it is different translation of national characters like æøå, but other times it might be a timezone difference as there is 1 hour diff between the 2 mails, and in some situations the dates are missing (So thunderbird assumes it is today)

But as said I will continue my manual process and will live with some duplicates.

Enabling the "maybee" should not cause unwanted deletes assuming the mails has a proper messageID

**Comment by eyalroz** [comment]
> Enabling the "maybee" should not cause unwanted deletes assuming the mails has a proper messageID

Yes, but - it's a dangerous assumption.

If you can show me evidence that this occurs more frequently - or even that it _used_ to occur frequently years ago - I would seriously consider implementing the feature. For now, it's just one person seeing this.

Something you could do is:

1. Search for dupes while ignoring Message ID entirely.
2. Move the resulting dupe sets into a work folder other than the trash.
3. In that work folder, search _without_ ignoring Message ID, and delete the dupes you find

You will now remain only with the potential-dupes which differ by message ID. These you can process manually, or alternatively - use a different set of criteria to tell them apart.
