### ISSUE TITLE
improvement suggestion 2: which duplicates should be kept?

### ISSUE THREAD

**Issue by romykl** [eyalroz/removedupes#91]
2.	After searching for the duplicates, the user may choose which duplicates should be kept: First, Last, All or None. None invites misunderstandings. It could mean:
•	no one of the found and filtered mails shall be kept or
•	no duplicate mail shall be kept except for one.
Therefore the action of "None" must be explained, so the user knows what to expect from it. Pls. add this for user safety.

**Comment by eyalroz** [comment]
1. Pressing any of the buttons results in checkbox selection changes in the dialog.
2. There is no action named "None". It's keep "All copies", "No copies", "First copy" or "Last copy".  I don't believe that there is any way to interpret "No copies" as "no copies except one". 
3. Another safety measure is that, by default, duplicates are moved to Trash, so one can simply undo the move.
