### ISSUE TITLE
improvement suggestion 3: Keep First or Last duplicate?

### ISSUE THREAD

**Issue by romykl** [eyalroz/removedupes#92]
3. After searching for the duplicates, the user may choose which duplicates should be kept, here e.g.: First and Last. This supposes a certain "known" order leads to a first and last duplicate mail to be listed. This order however is not the same if title, date and time are the same. Because then they are ordered by their size, however sometimes from smaller to larger and sometimes the opposite. Therefore this is also misleading and not dealt the same way by the add-in for all duplicate groups. What is then the first/last criteria? This should also be explained in order to know which one to choose and why.

**Comment by eyalroz** [comment]
> This supposes a certain "known" order leads to a first and last duplicate mail to be listed

No, it doesn't. The choice is always relative to the current choice of order in the multi-column view.

> Because then they are ordered by their size, however sometimes from smaller to larger and sometimes the opposite.

Messages are ordered by what _you_ choose to order them by. It can be any one of the comparison criteria.

> This should also be explained in order to know which one to choose and why.

Pressing the button sets the checkbox selection, so you know what the effects are. It's true that the extension could use some documentation (e.g. on the wiki here), but I've not gotten complaints over the years of this being misleading or unclear.
