### ISSUE TITLE
Sorting by criterion column in dupe review dialog not working

### ISSUE THREAD

**Issue by romykl** [eyalroz/removedupes#93]
4.	The filter settings do not offer filtering duplicates by mail size. But maybe this should be included. If there is a reason why not, it should be explained.

**Comment by eyalroz** [comment]
"Filter settings"?

Anyway, message size is one of the supported message comparison criteria. Perhaps I'm misunderstanding - please explain.

**Comment by romykl** [comment]
Meant: in the duplicate message review window, the user has no influence on the order the duplicate groups are displayed, neither by date nor by size. But this helps when deciding on their removal.

**Comment by eyalroz** [comment]
> the user has no influence on the order the duplicate groups are displayed,

The user has control on the order of the display of each duplicate group, by pressing the appropriate column header.

**Comment by romykl** [comment]
That was what I initially tried. But this function seems not to function, Nothing changes in the order of the duplicates list regardless of which column header is clicked. Could it be a bug?

**Comment by eyalroz** [comment]
It could be a bug. Check the error console. It works for me...

**Comment by eyalroz** [comment]
If you're still seeing this problem, please reopen and post the relevant message/s from the error console.
