### ISSUE TITLE
Remove duplicates across accounts

### ISSUE THREAD

**Issue by mfouesneau** [eyalroz/removedupes#95]
Dear All, I'm discovering this extension, and it sounds great.
I cannot manage to find duplicates across accounts. If I select the inbox of account 1 and inbox of account 2 (and I know there are duplicates), it finds nothing...

(I removed the skip special folders)

**Comment by eyalroz** [comment]
You need to relax the comparison criteria. For example, if the folder name is used as a criterion, you will never find duplicates in different folders, only within folders. Or - a minor difference such as a few more empty lines may be distinguishing the supposed dupes. Gradually relax the criteria until you find the dupes you are expecting - but be careful not to relax them too far.

**Comment by mfouesneau** [comment]
I tried many option combinations it finds some obvious matches when I relax entirely the rules but does not find really identical messages.

To be even clearer, I copy a message from one folder to another and it does not find those.

**Comment by eyalroz** [comment]
@mfouesneau : 

1. What happens when you drop all criteria?
2. Please check the Error Console (on the menus, under Tools | Developer Tools). If anything there mentions removedupes, please copy it here.

**Comment by mfouesneau** [comment]
1. I get the entire folder which is not just duplicates. I tried various options there, and when send time it a criteria I still get messages from the same folder (not sent at the same time) to be "duplicates"
2. No message at all.

**Comment by mfouesneau** [comment]
It seems that the body & number of lines & message size are different for the two accounts. Something I do not understand since the content of the messages at least should be identical. Headers may be changed depending on the routing.

**Comment by eyalroz** [comment]
@mfouesneau : So, Thunderbird sometimes appends one or two empty lines, and not necessarily consistently. Unfortunately, I can't tell whether the line number is "trustworthy" or not, so if you use number of lines, or body, this may show up as a difference.

**Comment by eyalroz** [comment]
Closing, as removing across accounts does work.
