### ISSUE TITLE
Wrong URL on the removedupes main page

### ISSUE THREAD

**Issue by Bricolas** [eyalroz/removedupes#96]
Dear developer,

I want to tell you that the url on the top right of the [Github page](https://github.com/eyalroz/removedupes/issues/new) is wrong :
https://addons.thunderbird.net/en-US/thunderbird/addon/remove-duplicate-messages-alte/ is broken.

By the way, the email on the bottom of this main page (you can [write me](mailto:eyalroz@technion.ac.il).) is rejecting the emails.
_550 5.4.1 Recipient address rejected: Access denied. AS(201806281) [[DB5EUR01FT052.eop-EUR01.prod.protection.outlook.com](http://db5eur01ft052.eop-eur01.prod.protection.outlook.com/)]_

Best regards,

Bricolas

**Comment by eyalroz** [comment]
Thanks, fixed the URL and will soon fix the email.
